<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>waad-world</RootNamespace>
    <AssemblyName>waad-world</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE;ENABLE_DATABASE_MYSQL;ENABLE_DATABASE_POSTGRES;ENABLE_DATABASE_SQLITE</DefineConstants>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>portable</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>RELEASE;TRACE;ENABLE_DATABASE_MYSQL;ENABLE_DATABASE_POSTGRES;ENABLE_DATABASE_SQLITE</DefineConstants>
    <TieredCompilation>true</TieredCompilation>
    <ReadyToRun>true</ReadyToRun>
    <PublishReadyToRun>true</PublishReadyToRun>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <DefineConstants>WINDOWS;WIN32;$(DefineConstants);CONFIG_USE_IOCP</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'Linux'">
    <OutputPath>bin/$(Configuration)/</OutputPath>
    <DefineConstants>LINUX;$(DefineConstants);CONFIG_USE_EPOLL</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'FreeBSD' Or '$(OS)' == 'DragonFly'">
    <OutputPath>bin/$(Configuration)/</OutputPath>
    <DefineConstants>FREEBSD;$(DefineConstants);CONFIG_USE_KQUEUE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\binaries\shared\waad-shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\CoreWaad\src\world\**\*.cs" Exclude="obj\**\*.cs" />
    <Content Include="..\..\..\CoreWaad\src\world\**\*" Exclude="obj\**\*.cs;**\*.cs" CopyToOutputDirectory="Always" />
  </ItemGroup>

  <Target Name="GenerateGitInfo" BeforeTargets="BeforeBuild">
      <Exec WorkingDirectory="$(MSBuildThisFileDirectory)"
        Command="dotnet run --project &quot;$(MSBuildThisFileDirectory)..\..\extras\GitExtractor\GitExtractor.csproj&quot; -- GenerateGitInfo &quot;$(MSBuildProjectDirectory)\GitInfo.txt&quot; &gt; &quot;$(MSBuildProjectDirectory)\GitInfoLog.txt&quot; 2&gt;&amp;1"
          ContinueOnError="WarnAndContinue" />
  </Target>

  <ItemGroup>
    <EmbeddedResource Include="GitInfo.txt" />
  </ItemGroup>

</Project>
