/*
 * Wow Arbonne Ascent Development MMORPG Server
 * Copyright (C) 2007-2025 WAAD Team <https://arbonne.games-rpg.net/>
 *
 * From original Ascent MMORPG Server, 2005-2008, which doesn't exist anymore.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Portage de UpdateFields.h — Version Tag: 335.12340.
// Les enums C++ sont exposés en const int car ils servent d'index dans les tableaux de valeurs d'update.

namespace WaadWorldServer;

public static class EObjectFields
{
    public const int OBJECT_FIELD_GUID    = 0x0000; // Size: 2, Type: LONG, Flags: PUBLIC
    public const int OBJECT_FIELD_TYPE    = 0x0002; // Size: 1, Type: INT, Flags: PUBLIC
    public const int OBJECT_FIELD_ENTRY   = 0x0003; // Size: 1, Type: INT, Flags: PUBLIC
    public const int OBJECT_FIELD_SCALE_X = 0x0004; // Size: 1, Type: FLOAT, Flags: PUBLIC
    public const int OBJECT_FIELD_PADDING = 0x0005; // Size: 1, Type: INT, Flags: NONE
    public const int OBJECT_END           = 0x0006;
}

public static class EItemFields
{
    private const int B = EObjectFields.OBJECT_END;

    public const int ITEM_FIELD_OWNER               = B + 0x0000; // Size: 2, Type: LONG, Flags: PUBLIC
    public const int ITEM_FIELD_CONTAINED           = B + 0x0002; // Size: 2, Type: LONG, Flags: PUBLIC
    public const int ITEM_FIELD_CREATOR             = B + 0x0004; // Size: 2, Type: LONG, Flags: PUBLIC
    public const int ITEM_FIELD_GIFTCREATOR         = B + 0x0006; // Size: 2, Type: LONG, Flags: PUBLIC
    public const int ITEM_FIELD_STACK_COUNT         = B + 0x0008; // Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER
    public const int ITEM_FIELD_DURATION            = B + 0x0009; // Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER
    public const int ITEM_FIELD_SPELL_CHARGES       = B + 0x000A; // Size: 5, Type: INT, Flags: OWNER, ITEM_OWNER
    public const int ITEM_FIELD_SPELL_CHARGES_1     = B + 0x000B;
    public const int ITEM_FIELD_SPELL_CHARGES_2     = B + 0x000C;
    public const int ITEM_FIELD_SPELL_CHARGES_3     = B + 0x000D;
    public const int ITEM_FIELD_SPELL_CHARGES_4     = B + 0x000E;
    public const int ITEM_FIELD_FLAGS               = B + 0x000F; // Size: 1, Type: INT, Flags: PUBLIC
    public const int ITEM_FIELD_ENCHANTMENT_1_1     = B + 0x0010; // Size: 2, Type: INT, Flags: PUBLIC
    public const int ITEM_FIELD_ENCHANTMENT_1_3     = B + 0x0012; // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    public const int ITEM_FIELD_ENCHANTMENT_2_1     = B + 0x0013;
    public const int ITEM_FIELD_ENCHANTMENT_2_3     = B + 0x0015;
    public const int ITEM_FIELD_ENCHANTMENT_3_1     = B + 0x0016;
    public const int ITEM_FIELD_ENCHANTMENT_3_3     = B + 0x0018;
    public const int ITEM_FIELD_ENCHANTMENT_4_1     = B + 0x0019;
    public const int ITEM_FIELD_ENCHANTMENT_4_3     = B + 0x001B;
    public const int ITEM_FIELD_ENCHANTMENT_5_1     = B + 0x001C;
    public const int ITEM_FIELD_ENCHANTMENT_5_3     = B + 0x001E;
    public const int ITEM_FIELD_ENCHANTMENT_6_1     = B + 0x001F;
    public const int ITEM_FIELD_ENCHANTMENT_6_3     = B + 0x0021;
    public const int ITEM_FIELD_ENCHANTMENT_7_1     = B + 0x0022;
    public const int ITEM_FIELD_ENCHANTMENT_7_3     = B + 0x0024;
    public const int ITEM_FIELD_ENCHANTMENT_8_1     = B + 0x0025;
    public const int ITEM_FIELD_ENCHANTMENT_8_3     = B + 0x0027;
    public const int ITEM_FIELD_ENCHANTMENT_9_1     = B + 0x0028;
    public const int ITEM_FIELD_ENCHANTMENT_9_3     = B + 0x002A;
    public const int ITEM_FIELD_ENCHANTMENT_10_1    = B + 0x002B;
    public const int ITEM_FIELD_ENCHANTMENT_10_3    = B + 0x002D;
    public const int ITEM_FIELD_ENCHANTMENT_11_1    = B + 0x002E;
    public const int ITEM_FIELD_ENCHANTMENT_11_3    = B + 0x0030;
    public const int ITEM_FIELD_ENCHANTMENT_12_1    = B + 0x0031;
    public const int ITEM_FIELD_ENCHANTMENT_12_3    = B + 0x0033;
    public const int ITEM_FIELD_PROPERTY_SEED       = B + 0x0034; // Size: 1, Type: INT, Flags: PUBLIC
    public const int ITEM_FIELD_RANDOM_PROPERTIES_ID = B + 0x0035; // Size: 1, Type: INT, Flags: PUBLIC
    public const int ITEM_FIELD_DURABILITY          = B + 0x0036; // Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER
    public const int ITEM_FIELD_MAXDURABILITY       = B + 0x0037; // Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER
    public const int ITEM_FIELD_CREATE_PLAYED_TIME  = B + 0x0038; // Size: 1, Type: INT, Flags: PUBLIC
    public const int ITEM_FIELD_PAD                 = B + 0x0039; // Size: 1, Type: INT, Flags: NONE
    public const int ITEM_END                       = B + 0x003A;
}

public static class EContainerFields
{
    private const int B = EItemFields.ITEM_END;

    public const int CONTAINER_FIELD_NUM_SLOTS = B + 0x0000; // Size: 1, Type: INT, Flags: PUBLIC — nombre d'emplacements (Byte[0])
    public const int CONTAINER_ALIGN_PAD       = B + 0x0001; // Size: 1, Type: BYTES, Flags: NONE
    public const int CONTAINER_FIELD_SLOT_0    = B + 0x0002; // Size: 72, Type: LONG, Flags: PUBLIC — 72 emplacements
    public const int
        CONTAINER_FIELD_SLOT_1 = CONTAINER_FIELD_SLOT_0 + 1, CONTAINER_FIELD_SLOT_2 = CONTAINER_FIELD_SLOT_0 + 2,
        CONTAINER_FIELD_SLOT_3 = CONTAINER_FIELD_SLOT_0 + 3, CONTAINER_FIELD_SLOT_4 = CONTAINER_FIELD_SLOT_0 + 4,
        CONTAINER_FIELD_SLOT_5 = CONTAINER_FIELD_SLOT_0 + 5, CONTAINER_FIELD_SLOT_6 = CONTAINER_FIELD_SLOT_0 + 6,
        CONTAINER_FIELD_SLOT_7 = CONTAINER_FIELD_SLOT_0 + 7, CONTAINER_FIELD_SLOT_8 = CONTAINER_FIELD_SLOT_0 + 8,
        CONTAINER_FIELD_SLOT_9 = CONTAINER_FIELD_SLOT_0 + 9, CONTAINER_FIELD_SLOT_10 = CONTAINER_FIELD_SLOT_0 + 10,
        CONTAINER_FIELD_SLOT_11 = CONTAINER_FIELD_SLOT_0 + 11, CONTAINER_FIELD_SLOT_12 = CONTAINER_FIELD_SLOT_0 + 12,
        CONTAINER_FIELD_SLOT_13 = CONTAINER_FIELD_SLOT_0 + 13, CONTAINER_FIELD_SLOT_14 = CONTAINER_FIELD_SLOT_0 + 14,
        CONTAINER_FIELD_SLOT_15 = CONTAINER_FIELD_SLOT_0 + 15, CONTAINER_FIELD_SLOT_16 = CONTAINER_FIELD_SLOT_0 + 16,
        CONTAINER_FIELD_SLOT_17 = CONTAINER_FIELD_SLOT_0 + 17, CONTAINER_FIELD_SLOT_18 = CONTAINER_FIELD_SLOT_0 + 18,
        CONTAINER_FIELD_SLOT_19 = CONTAINER_FIELD_SLOT_0 + 19, CONTAINER_FIELD_SLOT_20 = CONTAINER_FIELD_SLOT_0 + 20,
        CONTAINER_FIELD_SLOT_21 = CONTAINER_FIELD_SLOT_0 + 21, CONTAINER_FIELD_SLOT_22 = CONTAINER_FIELD_SLOT_0 + 22,
        CONTAINER_FIELD_SLOT_23 = CONTAINER_FIELD_SLOT_0 + 23, CONTAINER_FIELD_SLOT_24 = CONTAINER_FIELD_SLOT_0 + 24,
        CONTAINER_FIELD_SLOT_25 = CONTAINER_FIELD_SLOT_0 + 25, CONTAINER_FIELD_SLOT_26 = CONTAINER_FIELD_SLOT_0 + 26,
        CONTAINER_FIELD_SLOT_27 = CONTAINER_FIELD_SLOT_0 + 27, CONTAINER_FIELD_SLOT_28 = CONTAINER_FIELD_SLOT_0 + 28,
        CONTAINER_FIELD_SLOT_29 = CONTAINER_FIELD_SLOT_0 + 29, CONTAINER_FIELD_SLOT_30 = CONTAINER_FIELD_SLOT_0 + 30,
        CONTAINER_FIELD_SLOT_31 = CONTAINER_FIELD_SLOT_0 + 31, CONTAINER_FIELD_SLOT_32 = CONTAINER_FIELD_SLOT_0 + 32,
        CONTAINER_FIELD_SLOT_33 = CONTAINER_FIELD_SLOT_0 + 33, CONTAINER_FIELD_SLOT_34 = CONTAINER_FIELD_SLOT_0 + 34,
        CONTAINER_FIELD_SLOT_35 = CONTAINER_FIELD_SLOT_0 + 35, CONTAINER_FIELD_SLOT_36 = CONTAINER_FIELD_SLOT_0 + 36,
        CONTAINER_FIELD_SLOT_37 = CONTAINER_FIELD_SLOT_0 + 37, CONTAINER_FIELD_SLOT_38 = CONTAINER_FIELD_SLOT_0 + 38,
        CONTAINER_FIELD_SLOT_39 = CONTAINER_FIELD_SLOT_0 + 39, CONTAINER_FIELD_SLOT_40 = CONTAINER_FIELD_SLOT_0 + 40,
        CONTAINER_FIELD_SLOT_41 = CONTAINER_FIELD_SLOT_0 + 41, CONTAINER_FIELD_SLOT_42 = CONTAINER_FIELD_SLOT_0 + 42,
        CONTAINER_FIELD_SLOT_43 = CONTAINER_FIELD_SLOT_0 + 43, CONTAINER_FIELD_SLOT_44 = CONTAINER_FIELD_SLOT_0 + 44,
        CONTAINER_FIELD_SLOT_45 = CONTAINER_FIELD_SLOT_0 + 45, CONTAINER_FIELD_SLOT_46 = CONTAINER_FIELD_SLOT_0 + 46,
        CONTAINER_FIELD_SLOT_47 = CONTAINER_FIELD_SLOT_0 + 47, CONTAINER_FIELD_SLOT_48 = CONTAINER_FIELD_SLOT_0 + 48,
        CONTAINER_FIELD_SLOT_49 = CONTAINER_FIELD_SLOT_0 + 49, CONTAINER_FIELD_SLOT_50 = CONTAINER_FIELD_SLOT_0 + 50,
        CONTAINER_FIELD_SLOT_51 = CONTAINER_FIELD_SLOT_0 + 51, CONTAINER_FIELD_SLOT_52 = CONTAINER_FIELD_SLOT_0 + 52,
        CONTAINER_FIELD_SLOT_53 = CONTAINER_FIELD_SLOT_0 + 53, CONTAINER_FIELD_SLOT_54 = CONTAINER_FIELD_SLOT_0 + 54,
        CONTAINER_FIELD_SLOT_55 = CONTAINER_FIELD_SLOT_0 + 55, CONTAINER_FIELD_SLOT_56 = CONTAINER_FIELD_SLOT_0 + 56,
        CONTAINER_FIELD_SLOT_57 = CONTAINER_FIELD_SLOT_0 + 57, CONTAINER_FIELD_SLOT_58 = CONTAINER_FIELD_SLOT_0 + 58,
        CONTAINER_FIELD_SLOT_59 = CONTAINER_FIELD_SLOT_0 + 59, CONTAINER_FIELD_SLOT_60 = CONTAINER_FIELD_SLOT_0 + 60,
        CONTAINER_FIELD_SLOT_61 = CONTAINER_FIELD_SLOT_0 + 61, CONTAINER_FIELD_SLOT_62 = CONTAINER_FIELD_SLOT_0 + 62,
        CONTAINER_FIELD_SLOT_63 = CONTAINER_FIELD_SLOT_0 + 63, CONTAINER_FIELD_SLOT_64 = CONTAINER_FIELD_SLOT_0 + 64,
        CONTAINER_FIELD_SLOT_65 = CONTAINER_FIELD_SLOT_0 + 65, CONTAINER_FIELD_SLOT_66 = CONTAINER_FIELD_SLOT_0 + 66,
        CONTAINER_FIELD_SLOT_67 = CONTAINER_FIELD_SLOT_0 + 67, CONTAINER_FIELD_SLOT_68 = CONTAINER_FIELD_SLOT_0 + 68,
        CONTAINER_FIELD_SLOT_69 = CONTAINER_FIELD_SLOT_0 + 69, CONTAINER_FIELD_SLOT_70 = CONTAINER_FIELD_SLOT_0 + 70,
        CONTAINER_FIELD_SLOT_71 = CONTAINER_FIELD_SLOT_0 + 71;
    public const int CONTAINER_END = B + 0x004A;
}

public static class EUnitFields
{
    private const int B = EObjectFields.OBJECT_END;

    public const int UNIT_FIELD_CHARM          = B + 0x0000; // Size: 2, Type: LONG, Flags: PUBLIC — GUID cible
    public const int UNIT_FIELD_SUMMON         = B + 0x0002; // Size: 2, Type: LONG, Flags: PUBLIC — GUID cible
    public const int UNIT_FIELD_CRITTER        = B + 0x0004; // Size: 2, Type: LONG, Flags: PRIVATE — inutilisé
    public const int UNIT_FIELD_CHARMEDBY      = B + 0x0006; // Size: 2, Type: LONG, Flags: PUBLIC — GUID propriétaire
    public const int UNIT_FIELD_SUMMONEDBY     = B + 0x0008; // Size: 2, Type: LONG, Flags: PUBLIC — GUID propriétaire
    public const int UNIT_FIELD_CREATEDBY      = B + 0x000A; // Size: 2, Type: LONG, Flags: PUBLIC — GUID propriétaire
    public const int UNIT_FIELD_TARGET         = B + 0x000C; // Size: 2, Type: LONG, Flags: PUBLIC — GUID cible
    public const int UNIT_FIELD_CHANNEL_OBJECT = B + 0x000E; // Size: 2, Type: LONG, Flags: PUBLIC — GUID cible du sort
    public const int UNIT_CHANNEL_SPELL        = B + 0x0010; // Size: 1, Type: INT, Flags: PUBLIC — SpellId
    public const int UNIT_FIELD_BYTES_0        = B + 0x0011; // Size: 1, Type: BYTES, Flags: PUBLIC — [3:TypePower] [2:Genre] [1:Type] [0:Race/Famille]
    public const int UNIT_FIELD_HEALTH         = B + 0x0012; // Size: 1, Type: INT, Flags: PUBLIC
    public const int UNIT_FIELD_POWER1         = B + 0x0013; // Mana
    public const int UNIT_FIELD_POWER2         = B + 0x0014; // Rage
    public const int UNIT_FIELD_POWER3         = B + 0x0015; // Focus
    public const int UNIT_FIELD_POWER4         = B + 0x0016; // Énergie
    public const int UNIT_FIELD_POWER5         = B + 0x0017; // Bonheur familier (1 à 3)
    public const int UNIT_FIELD_POWER6         = B + 0x0018; // Runes
    public const int UNIT_FIELD_POWER7         = B + 0x0019; // Puissance runique
    public const int UNIT_FIELD_MAXHEALTH      = B + 0x001A;
    public const int UNIT_FIELD_MAXPOWER1      = B + 0x001B; // Mana
    public const int UNIT_FIELD_MAXPOWER2      = B + 0x001C; // Rage
    public const int UNIT_FIELD_MAXPOWER3      = B + 0x001D; // Focus
    public const int UNIT_FIELD_MAXPOWER4      = B + 0x001E; // Énergie
    public const int UNIT_FIELD_MAXPOWER5      = B + 0x001F; // Bonheur
    public const int UNIT_FIELD_MAXPOWER6      = B + 0x0020; // Runes
    public const int UNIT_FIELD_MAXPOWER7      = B + 0x0021; // Puissance runique
    public const int UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER   = B + 0x0022; // Size: 7, Type: INT, Flags: PUBLIC
    public const int UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER_1 = B + 0x0023;
    public const int UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER_2 = B + 0x0024;
    public const int UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER_3 = B + 0x0025;
    public const int UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER_4 = B + 0x0026;
    public const int UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER_5 = B + 0x0027;
    public const int UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER_6 = B + 0x0028;
    public const int UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER   = B + 0x0029; // Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER_1 = B + 0x002A;
    public const int UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER_2 = B + 0x002B;
    public const int UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER_3 = B + 0x002C;
    public const int UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER_4 = B + 0x002D;
    public const int UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER_5 = B + 0x002E;
    public const int UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER_6 = B + 0x002F;
    public const int UNIT_FIELD_LEVEL             = B + 0x0030; // Size: 1, Type: INT, Flags: PUBLIC
    public const int UNIT_FIELD_FACTIONTEMPLATE   = B + 0x0031; // Size: 1, Type: INT, Flags: PUBLIC
    public const int UNIT_VIRTUAL_ITEM_SLOT_ID    = B + 0x0032; // Size: 3, Type: INT, Flags: PUBLIC
    public const int UNIT_VIRTUAL_ITEM_SLOT_ID_1  = B + 0x0033;
    public const int UNIT_VIRTUAL_ITEM_SLOT_ID_2  = B + 0x0034;
    public const int UNIT_FIELD_FLAGS             = B + 0x0035; // Size: 1, Type: INT, Flags: PUBLIC
    public const int UNIT_FIELD_FLAGS_2           = B + 0x0036; // Size: 1, Type: INT, Flags: PUBLIC
    public const int UNIT_FIELD_AURASTATE         = B + 0x0037; // Size: 1, Type: INT, Flags: PUBLIC
    public const int UNIT_FIELD_BASEATTACKTIME    = B + 0x0038; // Size: 2, Type: INT, Flags: PUBLIC
    public const int UNIT_FIELD_RANGEDATTACKTIME  = B + 0x003A; // Size: 1, Type: INT, Flags: PRIVATE
    public const int UNIT_FIELD_BOUNDINGRADIUS    = B + 0x003B; // Size: 1, Type: FLOAT, Flags: PUBLIC
    public const int UNIT_FIELD_COMBATREACH       = B + 0x003C; // Size: 1, Type: FLOAT, Flags: PUBLIC
    public const int UNIT_FIELD_DISPLAYID         = B + 0x003D; // Size: 1, Type: INT, Flags: PUBLIC
    public const int UNIT_FIELD_NATIVEDISPLAYID   = B + 0x003E; // Size: 1, Type: INT, Flags: PUBLIC
    public const int UNIT_FIELD_MOUNTDISPLAYID    = B + 0x003F; // Size: 1, Type: INT, Flags: PUBLIC
    public const int UNIT_FIELD_MINDAMAGE         = B + 0x0040; // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
    public const int UNIT_FIELD_MAXDAMAGE         = B + 0x0041;
    public const int UNIT_FIELD_MINOFFHANDDAMAGE  = B + 0x0042;
    public const int UNIT_FIELD_MAXOFFHANDDAMAGE  = B + 0x0043;
    public const int UNIT_FIELD_BYTES_1           = B + 0x0044; // Size: 1, Type: BYTES, Flags: PUBLIC — [3:AttackState] [2:?] [1:TalentPoints] [0:StandState]
    public const int UNIT_FIELD_PET_LGUID         = B + 0x0045; // Size: 1, Type: INT, Flags: PUBLIC
    public const int UNIT_FIELD_PET_NAME_TIMESTAMP = B + 0x0046; // Size: 1, Type: INT, Flags: PUBLIC
    public const int UNIT_FIELD_PETEXPERIENCE     = B + 0x0047; // Size: 1, Type: INT, Flags: OWNER
    public const int UNIT_FIELD_PETNEXTLEVELEXP   = B + 0x0048; // Size: 1, Type: INT, Flags: OWNER
    public const int UNIT_DYNAMIC_FLAGS           = B + 0x0049; // Size: 1, Type: INT, Flags: DYNAMIC
    public const int UNIT_MOD_CAST_SPEED          = B + 0x004A; // Size: 1, Type: FLOAT, Flags: PUBLIC
    public const int UNIT_CREATED_BY_SPELL        = B + 0x004B; // Size: 1, Type: INT, Flags: PUBLIC
    public const int UNIT_NPC_FLAGS               = B + 0x004C; // Size: 1, Type: INT, Flags: DYNAMIC
    public const int UNIT_NPC_EMOTESTATE          = B + 0x004D; // Size: 1, Type: INT, Flags: PUBLIC
    public const int UNIT_FIELD_STAT0             = B + 0x004E; // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_STAT1             = B + 0x004F;
    public const int UNIT_FIELD_STAT2             = B + 0x0050;
    public const int UNIT_FIELD_STAT3             = B + 0x0051;
    public const int UNIT_FIELD_STAT4             = B + 0x0052;
    public const int UNIT_FIELD_POSSTAT0          = B + 0x0053;
    public const int UNIT_FIELD_POSSTAT1          = B + 0x0054;
    public const int UNIT_FIELD_POSSTAT2          = B + 0x0055;
    public const int UNIT_FIELD_POSSTAT3          = B + 0x0056;
    public const int UNIT_FIELD_POSSTAT4          = B + 0x0057;
    public const int UNIT_FIELD_NEGSTAT0          = B + 0x0058;
    public const int UNIT_FIELD_NEGSTAT1          = B + 0x0059;
    public const int UNIT_FIELD_NEGSTAT2          = B + 0x005A;
    public const int UNIT_FIELD_NEGSTAT3          = B + 0x005B;
    public const int UNIT_FIELD_NEGSTAT4          = B + 0x005C;
    public const int UNIT_FIELD_RESISTANCES       = B + 0x005D; // Size: 7, Type: INT, Flags: PRIVATE, OWNER — Armure
    public const int UNIT_FIELD_RESISTANCES_1     = B + 0x005E; // Sacré
    public const int UNIT_FIELD_RESISTANCES_2     = B + 0x005F; // Feu
    public const int UNIT_FIELD_RESISTANCES_3     = B + 0x0060; // Nature
    public const int UNIT_FIELD_RESISTANCES_4     = B + 0x0061; // Givre
    public const int UNIT_FIELD_RESISTANCES_5     = B + 0x0062; // Ombre
    public const int UNIT_FIELD_RESISTANCES_6     = B + 0x0063; // Arcane
    public const int UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE   = B + 0x0064; // Size: 7, Type: INT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE_1 = B + 0x0065;
    public const int UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE_2 = B + 0x0066;
    public const int UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE_3 = B + 0x0067;
    public const int UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE_4 = B + 0x0068;
    public const int UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE_5 = B + 0x0069;
    public const int UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE_6 = B + 0x006A;
    public const int UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE   = B + 0x006B; // Size: 7, Type: INT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE_1 = B + 0x006C;
    public const int UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE_2 = B + 0x006D;
    public const int UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE_3 = B + 0x006E;
    public const int UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE_4 = B + 0x006F;
    public const int UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE_5 = B + 0x0070;
    public const int UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE_6 = B + 0x0071;
    public const int UNIT_FIELD_BASE_MANA         = B + 0x0072; // Size: 1, Type: INT, Flags: PUBLIC
    public const int UNIT_FIELD_BASE_HEALTH       = B + 0x0073; // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_BYTES_2           = B + 0x0074; // Size: 1, Type: BYTES, Flags: PUBLIC — [3:ShapeType] [2:PetRename] [1:FlagPvPType] [0:Arme rengainée/sortie]
    public const int UNIT_FIELD_ATTACK_POWER      = B + 0x0075; // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_ATTACK_POWER_MODS = B + 0x0076; // Size: 1, Type: TWO_SHORT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_ATTACK_POWER_MULTIPLIER        = B + 0x0077; // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_RANGED_ATTACK_POWER            = B + 0x0078; // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_RANGED_ATTACK_POWER_MODS       = B + 0x0079; // Size: 1, Type: TWO_SHORT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER = B + 0x007A; // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_MINRANGEDDAMAGE   = B + 0x007B; // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_MAXRANGEDDAMAGE   = B + 0x007C; // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_POWER_COST_MODIFIER   = B + 0x007D; // Size: 7, Type: INT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_POWER_COST_MODIFIER_1 = B + 0x007E;
    public const int UNIT_FIELD_POWER_COST_MODIFIER_2 = B + 0x007F;
    public const int UNIT_FIELD_POWER_COST_MODIFIER_3 = B + 0x0080;
    public const int UNIT_FIELD_POWER_COST_MODIFIER_4 = B + 0x0081;
    public const int UNIT_FIELD_POWER_COST_MODIFIER_5 = B + 0x0082;
    public const int UNIT_FIELD_POWER_COST_MODIFIER_6 = B + 0x0083;
    public const int UNIT_FIELD_POWER_COST_MULTIPLIER   = B + 0x0084; // Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_POWER_COST_MULTIPLIER_1 = B + 0x0085;
    public const int UNIT_FIELD_POWER_COST_MULTIPLIER_2 = B + 0x0086;
    public const int UNIT_FIELD_POWER_COST_MULTIPLIER_3 = B + 0x0087;
    public const int UNIT_FIELD_POWER_COST_MULTIPLIER_4 = B + 0x0088;
    public const int UNIT_FIELD_POWER_COST_MULTIPLIER_5 = B + 0x0089;
    public const int UNIT_FIELD_POWER_COST_MULTIPLIER_6 = B + 0x008A;
    public const int UNIT_FIELD_MAXHEALTHMODIFIER = B + 0x008B; // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
    public const int UNIT_FIELD_HOVERHEIGHT       = B + 0x008C; // Size: 1, Type: FLOAT, Flags: PUBLIC
    public const int UNIT_FIELD_PADDING           = B + 0x008D; // Size: 1, Type: INT, Flags: NONE
    public const int UNIT_END                     = B + 0x008E;

    // Champs manuels (#define C++)
    public const int UNIT_FIELD_STRENGTH  = UNIT_FIELD_STAT0;
    public const int UNIT_FIELD_AGILITY   = UNIT_FIELD_STAT1;
    public const int UNIT_FIELD_STAMINA   = UNIT_FIELD_STAT2;
    public const int UNIT_FIELD_INTELLECT = UNIT_FIELD_STAT3;
    public const int UNIT_FIELD_SPIRIT    = UNIT_FIELD_STAT4;
}

public static class EPlayerFields
{
    private const int B = EUnitFields.UNIT_END;

    public const int PLAYER_DUEL_ARBITER    = B + 0x0000; // Size: 2, Type: LONG, Flags: PUBLIC
    public const int PLAYER_FLAGS           = B + 0x0002; // Size: 1, Type: INT, Flags: PUBLIC
    public const int PLAYER_GUILDID         = B + 0x0003; // Size: 1, Type: INT, Flags: PUBLIC
    public const int PLAYER_GUILDRANK       = B + 0x0004; // Size: 1, Type: INT, Flags: PUBLIC
    public const int PLAYER_BYTES           = B + 0x0005; // Size: 1, Type: BYTES, Flags: PUBLIC — [3:HairColor] [2:HairStyle] [1:Face] [0:Skin]
    public const int PLAYER_BYTES_2         = B + 0x0006; // Size: 1, Type: BYTES, Flags: PUBLIC — [3:RestedState] [2:BankSlot] [1:GM On/Off] [0:FacialHair]
    public const int PLAYER_BYTES_3         = B + 0x0007; // Size: 1, Type: BYTES, Flags: PUBLIC — [3:PvpRank] [2:?] [1:DrunkState] [0:Genre]
    public const int PLAYER_DUEL_TEAM       = B + 0x0008; // Size: 1, Type: INT, Flags: PUBLIC
    public const int PLAYER_GUILD_TIMESTAMP = B + 0x0009; // Size: 1, Type: INT, Flags: PUBLIC

    // Journal de quêtes : 25 entrées de 5 DWORD — _1: QuestId (PARTY_MEMBER), _2: état, _3: compteurs (2x TWO_SHORT), _5: timer.
    public const int PLAYER_QUEST_LOG_1_1  = B + 0x000A, PLAYER_QUEST_LOG_1_2  = B + 0x000B, PLAYER_QUEST_LOG_1_3  = B + 0x000C, PLAYER_QUEST_LOG_1_5  = B + 0x000E;
    public const int PLAYER_QUEST_LOG_2_1  = B + 0x000F, PLAYER_QUEST_LOG_2_2  = B + 0x0010, PLAYER_QUEST_LOG_2_3  = B + 0x0011, PLAYER_QUEST_LOG_2_5  = B + 0x0013;
    public const int PLAYER_QUEST_LOG_3_1  = B + 0x0014, PLAYER_QUEST_LOG_3_2  = B + 0x0015, PLAYER_QUEST_LOG_3_3  = B + 0x0016, PLAYER_QUEST_LOG_3_5  = B + 0x0018;
    public const int PLAYER_QUEST_LOG_4_1  = B + 0x0019, PLAYER_QUEST_LOG_4_2  = B + 0x001A, PLAYER_QUEST_LOG_4_3  = B + 0x001B, PLAYER_QUEST_LOG_4_5  = B + 0x001D;
    public const int PLAYER_QUEST_LOG_5_1  = B + 0x001E, PLAYER_QUEST_LOG_5_2  = B + 0x001F, PLAYER_QUEST_LOG_5_3  = B + 0x0020, PLAYER_QUEST_LOG_5_5  = B + 0x0022;
    public const int PLAYER_QUEST_LOG_6_1  = B + 0x0023, PLAYER_QUEST_LOG_6_2  = B + 0x0024, PLAYER_QUEST_LOG_6_3  = B + 0x0025, PLAYER_QUEST_LOG_6_5  = B + 0x0027;
    public const int PLAYER_QUEST_LOG_7_1  = B + 0x0028, PLAYER_QUEST_LOG_7_2  = B + 0x0029, PLAYER_QUEST_LOG_7_3  = B + 0x002A, PLAYER_QUEST_LOG_7_5  = B + 0x002C;
    public const int PLAYER_QUEST_LOG_8_1  = B + 0x002D, PLAYER_QUEST_LOG_8_2  = B + 0x002E, PLAYER_QUEST_LOG_8_3  = B + 0x002F, PLAYER_QUEST_LOG_8_5  = B + 0x0031;
    public const int PLAYER_QUEST_LOG_9_1  = B + 0x0032, PLAYER_QUEST_LOG_9_2  = B + 0x0033, PLAYER_QUEST_LOG_9_3  = B + 0x0034, PLAYER_QUEST_LOG_9_5  = B + 0x0036;
    public const int PLAYER_QUEST_LOG_10_1 = B + 0x0037, PLAYER_QUEST_LOG_10_2 = B + 0x0038, PLAYER_QUEST_LOG_10_3 = B + 0x0039, PLAYER_QUEST_LOG_10_5 = B + 0x003B;
    public const int PLAYER_QUEST_LOG_11_1 = B + 0x003C, PLAYER_QUEST_LOG_11_2 = B + 0x003D, PLAYER_QUEST_LOG_11_3 = B + 0x003E, PLAYER_QUEST_LOG_11_5 = B + 0x0040;
    public const int PLAYER_QUEST_LOG_12_1 = B + 0x0041, PLAYER_QUEST_LOG_12_2 = B + 0x0042, PLAYER_QUEST_LOG_12_3 = B + 0x0043, PLAYER_QUEST_LOG_12_5 = B + 0x0045;
    public const int PLAYER_QUEST_LOG_13_1 = B + 0x0046, PLAYER_QUEST_LOG_13_2 = B + 0x0047, PLAYER_QUEST_LOG_13_3 = B + 0x0048, PLAYER_QUEST_LOG_13_5 = B + 0x004A;
    public const int PLAYER_QUEST_LOG_14_1 = B + 0x004B, PLAYER_QUEST_LOG_14_2 = B + 0x004C, PLAYER_QUEST_LOG_14_3 = B + 0x004D, PLAYER_QUEST_LOG_14_5 = B + 0x004F;
    public const int PLAYER_QUEST_LOG_15_1 = B + 0x0050, PLAYER_QUEST_LOG_15_2 = B + 0x0051, PLAYER_QUEST_LOG_15_3 = B + 0x0052, PLAYER_QUEST_LOG_15_5 = B + 0x0054;
    public const int PLAYER_QUEST_LOG_16_1 = B + 0x0055, PLAYER_QUEST_LOG_16_2 = B + 0x0056, PLAYER_QUEST_LOG_16_3 = B + 0x0057, PLAYER_QUEST_LOG_16_5 = B + 0x0059;
    public const int PLAYER_QUEST_LOG_17_1 = B + 0x005A, PLAYER_QUEST_LOG_17_2 = B + 0x005B, PLAYER_QUEST_LOG_17_3 = B + 0x005C, PLAYER_QUEST_LOG_17_5 = B + 0x005E;
    public const int PLAYER_QUEST_LOG_18_1 = B + 0x005F, PLAYER_QUEST_LOG_18_2 = B + 0x0060, PLAYER_QUEST_LOG_18_3 = B + 0x0061, PLAYER_QUEST_LOG_18_5 = B + 0x0063;
    public const int PLAYER_QUEST_LOG_19_1 = B + 0x0064, PLAYER_QUEST_LOG_19_2 = B + 0x0065, PLAYER_QUEST_LOG_19_3 = B + 0x0066, PLAYER_QUEST_LOG_19_5 = B + 0x0068;
    public const int PLAYER_QUEST_LOG_20_1 = B + 0x0069, PLAYER_QUEST_LOG_20_2 = B + 0x006A, PLAYER_QUEST_LOG_20_3 = B + 0x006B, PLAYER_QUEST_LOG_20_5 = B + 0x006D;
    public const int PLAYER_QUEST_LOG_21_1 = B + 0x006E, PLAYER_QUEST_LOG_21_2 = B + 0x006F, PLAYER_QUEST_LOG_21_3 = B + 0x0070, PLAYER_QUEST_LOG_21_5 = B + 0x0072;
    public const int PLAYER_QUEST_LOG_22_1 = B + 0x0073, PLAYER_QUEST_LOG_22_2 = B + 0x0074, PLAYER_QUEST_LOG_22_3 = B + 0x0075, PLAYER_QUEST_LOG_22_5 = B + 0x0077;
    public const int PLAYER_QUEST_LOG_23_1 = B + 0x0078, PLAYER_QUEST_LOG_23_2 = B + 0x0079, PLAYER_QUEST_LOG_23_3 = B + 0x007A, PLAYER_QUEST_LOG_23_5 = B + 0x007C;
    public const int PLAYER_QUEST_LOG_24_1 = B + 0x007D, PLAYER_QUEST_LOG_24_2 = B + 0x007E, PLAYER_QUEST_LOG_24_3 = B + 0x007F, PLAYER_QUEST_LOG_24_5 = B + 0x0081;
    public const int PLAYER_QUEST_LOG_25_1 = B + 0x0082, PLAYER_QUEST_LOG_25_2 = B + 0x0083, PLAYER_QUEST_LOG_25_3 = B + 0x0084, PLAYER_QUEST_LOG_25_5 = B + 0x0086;

    // Objets visibles : ENTRYID (INT) + ENCHANTMENT (TWO_SHORT), Flags: PUBLIC.
    public const int PLAYER_VISIBLE_ITEM_1_ENTRYID  = B + 0x0087, PLAYER_VISIBLE_ITEM_1_ENCHANTMENT  = B + 0x0088;
    public const int PLAYER_VISIBLE_ITEM_2_ENTRYID  = B + 0x0089, PLAYER_VISIBLE_ITEM_2_ENCHANTMENT  = B + 0x008A;
    public const int PLAYER_VISIBLE_ITEM_3_ENTRYID  = B + 0x008B, PLAYER_VISIBLE_ITEM_3_ENCHANTMENT  = B + 0x008C;
    public const int PLAYER_VISIBLE_ITEM_4_ENTRYID  = B + 0x008D, PLAYER_VISIBLE_ITEM_4_ENCHANTMENT  = B + 0x008E;
    public const int PLAYER_VISIBLE_ITEM_5_ENTRYID  = B + 0x008F, PLAYER_VISIBLE_ITEM_5_ENCHANTMENT  = B + 0x0090;
    public const int PLAYER_VISIBLE_ITEM_6_ENTRYID  = B + 0x0091, PLAYER_VISIBLE_ITEM_6_ENCHANTMENT  = B + 0x0092;
    public const int PLAYER_VISIBLE_ITEM_7_ENTRYID  = B + 0x0093, PLAYER_VISIBLE_ITEM_7_ENCHANTMENT  = B + 0x0094;
    public const int PLAYER_VISIBLE_ITEM_8_ENTRYID  = B + 0x0095, PLAYER_VISIBLE_ITEM_8_ENCHANTMENT  = B + 0x0096;
    public const int PLAYER_VISIBLE_ITEM_9_ENTRYID  = B + 0x0097, PLAYER_VISIBLE_ITEM_9_ENCHANTMENT  = B + 0x0098;
    public const int PLAYER_VISIBLE_ITEM_10_ENTRYID = B + 0x0099, PLAYER_VISIBLE_ITEM_10_ENCHANTMENT = B + 0x009A;
    public const int PLAYER_VISIBLE_ITEM_11_ENTRYID = B + 0x009B, PLAYER_VISIBLE_ITEM_11_ENCHANTMENT = B + 0x009C;
    public const int PLAYER_VISIBLE_ITEM_12_ENTRYID = B + 0x009D, PLAYER_VISIBLE_ITEM_12_ENCHANTMENT = B + 0x009E;
    public const int PLAYER_VISIBLE_ITEM_13_ENTRYID = B + 0x009F, PLAYER_VISIBLE_ITEM_13_ENCHANTMENT = B + 0x00A0;
    public const int PLAYER_VISIBLE_ITEM_14_ENTRYID = B + 0x00A1, PLAYER_VISIBLE_ITEM_14_ENCHANTMENT = B + 0x00A2;
    public const int PLAYER_VISIBLE_ITEM_15_ENTRYID = B + 0x00A3, PLAYER_VISIBLE_ITEM_15_ENCHANTMENT = B + 0x00A4;
    public const int PLAYER_VISIBLE_ITEM_16_ENTRYID = B + 0x00A5, PLAYER_VISIBLE_ITEM_16_ENCHANTMENT = B + 0x00A6;
    public const int PLAYER_VISIBLE_ITEM_17_ENTRYID = B + 0x00A7, PLAYER_VISIBLE_ITEM_17_ENCHANTMENT = B + 0x00A8;
    public const int PLAYER_VISIBLE_ITEM_18_ENTRYID = B + 0x00A9, PLAYER_VISIBLE_ITEM_18_ENCHANTMENT = B + 0x00AA;
    public const int PLAYER_VISIBLE_ITEM_19_ENTRYID = B + 0x00AB, PLAYER_VISIBLE_ITEM_19_ENCHANTMENT = B + 0x00AC;

    public const int PLAYER_CHOSEN_TITLE        = B + 0x00AD; // Size: 1, Type: INT, Flags: PUBLIC
    public const int PLAYER_FAKE_INEBRIATION    = B + 0x00AE; // Size: 1, Type: INT, Flags: PUBLIC
    public const int PLAYER_FIELD_PAD_0         = B + 0x00AF; // Size: 1, Type: INT, Flags: NONE

    public const int PLAYER_FIELD_INV_SLOT_HEAD = B + 0x00B0; // Size: 46, Type: LONG, Flags: PRIVATE
    public const int
        PLAYER_FIELD_INV_SLOT_HEAD_1 = PLAYER_FIELD_INV_SLOT_HEAD + 1, PLAYER_FIELD_INV_SLOT_HEAD_2 = PLAYER_FIELD_INV_SLOT_HEAD + 2,
        PLAYER_FIELD_INV_SLOT_HEAD_3 = PLAYER_FIELD_INV_SLOT_HEAD + 3, PLAYER_FIELD_INV_SLOT_HEAD_4 = PLAYER_FIELD_INV_SLOT_HEAD + 4,
        PLAYER_FIELD_INV_SLOT_HEAD_5 = PLAYER_FIELD_INV_SLOT_HEAD + 5, PLAYER_FIELD_INV_SLOT_HEAD_6 = PLAYER_FIELD_INV_SLOT_HEAD + 6,
        PLAYER_FIELD_INV_SLOT_HEAD_7 = PLAYER_FIELD_INV_SLOT_HEAD + 7, PLAYER_FIELD_INV_SLOT_HEAD_8 = PLAYER_FIELD_INV_SLOT_HEAD + 8,
        PLAYER_FIELD_INV_SLOT_HEAD_9 = PLAYER_FIELD_INV_SLOT_HEAD + 9, PLAYER_FIELD_INV_SLOT_HEAD_10 = PLAYER_FIELD_INV_SLOT_HEAD + 10,
        PLAYER_FIELD_INV_SLOT_HEAD_11 = PLAYER_FIELD_INV_SLOT_HEAD + 11, PLAYER_FIELD_INV_SLOT_HEAD_12 = PLAYER_FIELD_INV_SLOT_HEAD + 12,
        PLAYER_FIELD_INV_SLOT_HEAD_13 = PLAYER_FIELD_INV_SLOT_HEAD + 13, PLAYER_FIELD_INV_SLOT_HEAD_14 = PLAYER_FIELD_INV_SLOT_HEAD + 14,
        PLAYER_FIELD_INV_SLOT_HEAD_15 = PLAYER_FIELD_INV_SLOT_HEAD + 15, PLAYER_FIELD_INV_SLOT_HEAD_16 = PLAYER_FIELD_INV_SLOT_HEAD + 16,
        PLAYER_FIELD_INV_SLOT_HEAD_17 = PLAYER_FIELD_INV_SLOT_HEAD + 17, PLAYER_FIELD_INV_SLOT_HEAD_18 = PLAYER_FIELD_INV_SLOT_HEAD + 18,
        PLAYER_FIELD_INV_SLOT_HEAD_19 = PLAYER_FIELD_INV_SLOT_HEAD + 19, PLAYER_FIELD_INV_SLOT_HEAD_20 = PLAYER_FIELD_INV_SLOT_HEAD + 20,
        PLAYER_FIELD_INV_SLOT_HEAD_21 = PLAYER_FIELD_INV_SLOT_HEAD + 21, PLAYER_FIELD_INV_SLOT_HEAD_22 = PLAYER_FIELD_INV_SLOT_HEAD + 22,
        PLAYER_FIELD_INV_SLOT_HEAD_23 = PLAYER_FIELD_INV_SLOT_HEAD + 23, PLAYER_FIELD_INV_SLOT_HEAD_24 = PLAYER_FIELD_INV_SLOT_HEAD + 24,
        PLAYER_FIELD_INV_SLOT_HEAD_25 = PLAYER_FIELD_INV_SLOT_HEAD + 25, PLAYER_FIELD_INV_SLOT_HEAD_26 = PLAYER_FIELD_INV_SLOT_HEAD + 26,
        PLAYER_FIELD_INV_SLOT_HEAD_27 = PLAYER_FIELD_INV_SLOT_HEAD + 27, PLAYER_FIELD_INV_SLOT_HEAD_28 = PLAYER_FIELD_INV_SLOT_HEAD + 28,
        PLAYER_FIELD_INV_SLOT_HEAD_29 = PLAYER_FIELD_INV_SLOT_HEAD + 29, PLAYER_FIELD_INV_SLOT_HEAD_30 = PLAYER_FIELD_INV_SLOT_HEAD + 30,
        PLAYER_FIELD_INV_SLOT_HEAD_31 = PLAYER_FIELD_INV_SLOT_HEAD + 31, PLAYER_FIELD_INV_SLOT_HEAD_32 = PLAYER_FIELD_INV_SLOT_HEAD + 32,
        PLAYER_FIELD_INV_SLOT_HEAD_33 = PLAYER_FIELD_INV_SLOT_HEAD + 33, PLAYER_FIELD_INV_SLOT_HEAD_34 = PLAYER_FIELD_INV_SLOT_HEAD + 34,
        PLAYER_FIELD_INV_SLOT_HEAD_35 = PLAYER_FIELD_INV_SLOT_HEAD + 35, PLAYER_FIELD_INV_SLOT_HEAD_36 = PLAYER_FIELD_INV_SLOT_HEAD + 36,
        PLAYER_FIELD_INV_SLOT_HEAD_37 = PLAYER_FIELD_INV_SLOT_HEAD + 37, PLAYER_FIELD_INV_SLOT_HEAD_38 = PLAYER_FIELD_INV_SLOT_HEAD + 38,
        PLAYER_FIELD_INV_SLOT_HEAD_39 = PLAYER_FIELD_INV_SLOT_HEAD + 39, PLAYER_FIELD_INV_SLOT_HEAD_40 = PLAYER_FIELD_INV_SLOT_HEAD + 40,
        PLAYER_FIELD_INV_SLOT_HEAD_41 = PLAYER_FIELD_INV_SLOT_HEAD + 41, PLAYER_FIELD_INV_SLOT_HEAD_42 = PLAYER_FIELD_INV_SLOT_HEAD + 42,
        PLAYER_FIELD_INV_SLOT_HEAD_43 = PLAYER_FIELD_INV_SLOT_HEAD + 43, PLAYER_FIELD_INV_SLOT_HEAD_44 = PLAYER_FIELD_INV_SLOT_HEAD + 44,
        PLAYER_FIELD_INV_SLOT_HEAD_45 = PLAYER_FIELD_INV_SLOT_HEAD + 45;

    public const int PLAYER_FIELD_PACK_SLOT_1 = B + 0x00DE; // Size: 32, Type: LONG, Flags: PRIVATE
    public const int
        PLAYER_FIELD_PACK_SLOT_1_1 = PLAYER_FIELD_PACK_SLOT_1 + 1, PLAYER_FIELD_PACK_SLOT_1_2 = PLAYER_FIELD_PACK_SLOT_1 + 2,
        PLAYER_FIELD_PACK_SLOT_1_3 = PLAYER_FIELD_PACK_SLOT_1 + 3, PLAYER_FIELD_PACK_SLOT_1_4 = PLAYER_FIELD_PACK_SLOT_1 + 4,
        PLAYER_FIELD_PACK_SLOT_1_5 = PLAYER_FIELD_PACK_SLOT_1 + 5, PLAYER_FIELD_PACK_SLOT_1_6 = PLAYER_FIELD_PACK_SLOT_1 + 6,
        PLAYER_FIELD_PACK_SLOT_1_7 = PLAYER_FIELD_PACK_SLOT_1 + 7, PLAYER_FIELD_PACK_SLOT_1_8 = PLAYER_FIELD_PACK_SLOT_1 + 8,
        PLAYER_FIELD_PACK_SLOT_1_9 = PLAYER_FIELD_PACK_SLOT_1 + 9, PLAYER_FIELD_PACK_SLOT_1_10 = PLAYER_FIELD_PACK_SLOT_1 + 10,
        PLAYER_FIELD_PACK_SLOT_1_11 = PLAYER_FIELD_PACK_SLOT_1 + 11, PLAYER_FIELD_PACK_SLOT_1_12 = PLAYER_FIELD_PACK_SLOT_1 + 12,
        PLAYER_FIELD_PACK_SLOT_1_13 = PLAYER_FIELD_PACK_SLOT_1 + 13, PLAYER_FIELD_PACK_SLOT_1_14 = PLAYER_FIELD_PACK_SLOT_1 + 14,
        PLAYER_FIELD_PACK_SLOT_1_15 = PLAYER_FIELD_PACK_SLOT_1 + 15, PLAYER_FIELD_PACK_SLOT_1_16 = PLAYER_FIELD_PACK_SLOT_1 + 16,
        PLAYER_FIELD_PACK_SLOT_1_17 = PLAYER_FIELD_PACK_SLOT_1 + 17, PLAYER_FIELD_PACK_SLOT_1_18 = PLAYER_FIELD_PACK_SLOT_1 + 18,
        PLAYER_FIELD_PACK_SLOT_1_19 = PLAYER_FIELD_PACK_SLOT_1 + 19, PLAYER_FIELD_PACK_SLOT_1_20 = PLAYER_FIELD_PACK_SLOT_1 + 20,
        PLAYER_FIELD_PACK_SLOT_1_21 = PLAYER_FIELD_PACK_SLOT_1 + 21, PLAYER_FIELD_PACK_SLOT_1_22 = PLAYER_FIELD_PACK_SLOT_1 + 22,
        PLAYER_FIELD_PACK_SLOT_1_23 = PLAYER_FIELD_PACK_SLOT_1 + 23, PLAYER_FIELD_PACK_SLOT_1_24 = PLAYER_FIELD_PACK_SLOT_1 + 24,
        PLAYER_FIELD_PACK_SLOT_1_25 = PLAYER_FIELD_PACK_SLOT_1 + 25, PLAYER_FIELD_PACK_SLOT_1_26 = PLAYER_FIELD_PACK_SLOT_1 + 26,
        PLAYER_FIELD_PACK_SLOT_1_27 = PLAYER_FIELD_PACK_SLOT_1 + 27, PLAYER_FIELD_PACK_SLOT_1_28 = PLAYER_FIELD_PACK_SLOT_1 + 28,
        PLAYER_FIELD_PACK_SLOT_1_29 = PLAYER_FIELD_PACK_SLOT_1 + 29, PLAYER_FIELD_PACK_SLOT_1_30 = PLAYER_FIELD_PACK_SLOT_1 + 30,
        PLAYER_FIELD_PACK_SLOT_1_31 = PLAYER_FIELD_PACK_SLOT_1 + 31;

    public const int PLAYER_FIELD_BANK_SLOT_1 = B + 0x00FE; // Size: 56, Type: LONG, Flags: PRIVATE
    public const int
        PLAYER_FIELD_BANK_SLOT_1_1 = PLAYER_FIELD_BANK_SLOT_1 + 1, PLAYER_FIELD_BANK_SLOT_1_2 = PLAYER_FIELD_BANK_SLOT_1 + 2,
        PLAYER_FIELD_BANK_SLOT_1_3 = PLAYER_FIELD_BANK_SLOT_1 + 3, PLAYER_FIELD_BANK_SLOT_1_4 = PLAYER_FIELD_BANK_SLOT_1 + 4,
        PLAYER_FIELD_BANK_SLOT_1_5 = PLAYER_FIELD_BANK_SLOT_1 + 5, PLAYER_FIELD_BANK_SLOT_1_6 = PLAYER_FIELD_BANK_SLOT_1 + 6,
        PLAYER_FIELD_BANK_SLOT_1_7 = PLAYER_FIELD_BANK_SLOT_1 + 7, PLAYER_FIELD_BANK_SLOT_1_8 = PLAYER_FIELD_BANK_SLOT_1 + 8,
        PLAYER_FIELD_BANK_SLOT_1_9 = PLAYER_FIELD_BANK_SLOT_1 + 9, PLAYER_FIELD_BANK_SLOT_1_10 = PLAYER_FIELD_BANK_SLOT_1 + 10,
        PLAYER_FIELD_BANK_SLOT_1_11 = PLAYER_FIELD_BANK_SLOT_1 + 11, PLAYER_FIELD_BANK_SLOT_1_12 = PLAYER_FIELD_BANK_SLOT_1 + 12,
        PLAYER_FIELD_BANK_SLOT_1_13 = PLAYER_FIELD_BANK_SLOT_1 + 13, PLAYER_FIELD_BANK_SLOT_1_14 = PLAYER_FIELD_BANK_SLOT_1 + 14,
        PLAYER_FIELD_BANK_SLOT_1_15 = PLAYER_FIELD_BANK_SLOT_1 + 15, PLAYER_FIELD_BANK_SLOT_1_16 = PLAYER_FIELD_BANK_SLOT_1 + 16,
        PLAYER_FIELD_BANK_SLOT_1_17 = PLAYER_FIELD_BANK_SLOT_1 + 17, PLAYER_FIELD_BANK_SLOT_1_18 = PLAYER_FIELD_BANK_SLOT_1 + 18,
        PLAYER_FIELD_BANK_SLOT_1_19 = PLAYER_FIELD_BANK_SLOT_1 + 19, PLAYER_FIELD_BANK_SLOT_1_20 = PLAYER_FIELD_BANK_SLOT_1 + 20,
        PLAYER_FIELD_BANK_SLOT_1_21 = PLAYER_FIELD_BANK_SLOT_1 + 21, PLAYER_FIELD_BANK_SLOT_1_22 = PLAYER_FIELD_BANK_SLOT_1 + 22,
        PLAYER_FIELD_BANK_SLOT_1_23 = PLAYER_FIELD_BANK_SLOT_1 + 23, PLAYER_FIELD_BANK_SLOT_1_24 = PLAYER_FIELD_BANK_SLOT_1 + 24,
        PLAYER_FIELD_BANK_SLOT_1_25 = PLAYER_FIELD_BANK_SLOT_1 + 25, PLAYER_FIELD_BANK_SLOT_1_26 = PLAYER_FIELD_BANK_SLOT_1 + 26,
        PLAYER_FIELD_BANK_SLOT_1_27 = PLAYER_FIELD_BANK_SLOT_1 + 27, PLAYER_FIELD_BANK_SLOT_1_28 = PLAYER_FIELD_BANK_SLOT_1 + 28,
        PLAYER_FIELD_BANK_SLOT_1_29 = PLAYER_FIELD_BANK_SLOT_1 + 29, PLAYER_FIELD_BANK_SLOT_1_30 = PLAYER_FIELD_BANK_SLOT_1 + 30,
        PLAYER_FIELD_BANK_SLOT_1_31 = PLAYER_FIELD_BANK_SLOT_1 + 31, PLAYER_FIELD_BANK_SLOT_1_32 = PLAYER_FIELD_BANK_SLOT_1 + 32,
        PLAYER_FIELD_BANK_SLOT_1_33 = PLAYER_FIELD_BANK_SLOT_1 + 33, PLAYER_FIELD_BANK_SLOT_1_34 = PLAYER_FIELD_BANK_SLOT_1 + 34,
        PLAYER_FIELD_BANK_SLOT_1_35 = PLAYER_FIELD_BANK_SLOT_1 + 35, PLAYER_FIELD_BANK_SLOT_1_36 = PLAYER_FIELD_BANK_SLOT_1 + 36,
        PLAYER_FIELD_BANK_SLOT_1_37 = PLAYER_FIELD_BANK_SLOT_1 + 37, PLAYER_FIELD_BANK_SLOT_1_38 = PLAYER_FIELD_BANK_SLOT_1 + 38,
        PLAYER_FIELD_BANK_SLOT_1_39 = PLAYER_FIELD_BANK_SLOT_1 + 39, PLAYER_FIELD_BANK_SLOT_1_40 = PLAYER_FIELD_BANK_SLOT_1 + 40,
        PLAYER_FIELD_BANK_SLOT_1_41 = PLAYER_FIELD_BANK_SLOT_1 + 41, PLAYER_FIELD_BANK_SLOT_1_42 = PLAYER_FIELD_BANK_SLOT_1 + 42,
        PLAYER_FIELD_BANK_SLOT_1_43 = PLAYER_FIELD_BANK_SLOT_1 + 43, PLAYER_FIELD_BANK_SLOT_1_44 = PLAYER_FIELD_BANK_SLOT_1 + 44,
        PLAYER_FIELD_BANK_SLOT_1_45 = PLAYER_FIELD_BANK_SLOT_1 + 45, PLAYER_FIELD_BANK_SLOT_1_46 = PLAYER_FIELD_BANK_SLOT_1 + 46,
        PLAYER_FIELD_BANK_SLOT_1_47 = PLAYER_FIELD_BANK_SLOT_1 + 47, PLAYER_FIELD_BANK_SLOT_1_48 = PLAYER_FIELD_BANK_SLOT_1 + 48,
        PLAYER_FIELD_BANK_SLOT_1_49 = PLAYER_FIELD_BANK_SLOT_1 + 49, PLAYER_FIELD_BANK_SLOT_1_50 = PLAYER_FIELD_BANK_SLOT_1 + 50,
        PLAYER_FIELD_BANK_SLOT_1_51 = PLAYER_FIELD_BANK_SLOT_1 + 51, PLAYER_FIELD_BANK_SLOT_1_52 = PLAYER_FIELD_BANK_SLOT_1 + 52,
        PLAYER_FIELD_BANK_SLOT_1_53 = PLAYER_FIELD_BANK_SLOT_1 + 53, PLAYER_FIELD_BANK_SLOT_1_54 = PLAYER_FIELD_BANK_SLOT_1 + 54,
        PLAYER_FIELD_BANK_SLOT_1_55 = PLAYER_FIELD_BANK_SLOT_1 + 55;

    public const int PLAYER_FIELD_BANKBAG_SLOT_1 = B + 0x0136; // Size: 14, Type: LONG, Flags: PRIVATE
    public const int
        PLAYER_FIELD_BANKBAG_SLOT_1_1 = PLAYER_FIELD_BANKBAG_SLOT_1 + 1, PLAYER_FIELD_BANKBAG_SLOT_1_2 = PLAYER_FIELD_BANKBAG_SLOT_1 + 2,
        PLAYER_FIELD_BANKBAG_SLOT_1_3 = PLAYER_FIELD_BANKBAG_SLOT_1 + 3, PLAYER_FIELD_BANKBAG_SLOT_1_4 = PLAYER_FIELD_BANKBAG_SLOT_1 + 4,
        PLAYER_FIELD_BANKBAG_SLOT_1_5 = PLAYER_FIELD_BANKBAG_SLOT_1 + 5, PLAYER_FIELD_BANKBAG_SLOT_1_6 = PLAYER_FIELD_BANKBAG_SLOT_1 + 6,
        PLAYER_FIELD_BANKBAG_SLOT_1_7 = PLAYER_FIELD_BANKBAG_SLOT_1 + 7, PLAYER_FIELD_BANKBAG_SLOT_1_8 = PLAYER_FIELD_BANKBAG_SLOT_1 + 8,
        PLAYER_FIELD_BANKBAG_SLOT_1_9 = PLAYER_FIELD_BANKBAG_SLOT_1 + 9, PLAYER_FIELD_BANKBAG_SLOT_1_10 = PLAYER_FIELD_BANKBAG_SLOT_1 + 10,
        PLAYER_FIELD_BANKBAG_SLOT_1_11 = PLAYER_FIELD_BANKBAG_SLOT_1 + 11, PLAYER_FIELD_BANKBAG_SLOT_1_12 = PLAYER_FIELD_BANKBAG_SLOT_1 + 12,
        PLAYER_FIELD_BANKBAG_SLOT_1_13 = PLAYER_FIELD_BANKBAG_SLOT_1 + 13;

    public const int PLAYER_FIELD_VENDORBUYBACK_SLOT_1 = B + 0x0144; // Size: 24, Type: LONG, Flags: PRIVATE
    public const int
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1_1 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 1, PLAYER_FIELD_VENDORBUYBACK_SLOT_1_2 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 2,
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1_3 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 3, PLAYER_FIELD_VENDORBUYBACK_SLOT_1_4 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 4,
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1_5 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 5, PLAYER_FIELD_VENDORBUYBACK_SLOT_1_6 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 6,
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1_7 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 7, PLAYER_FIELD_VENDORBUYBACK_SLOT_1_8 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 8,
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1_9 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 9, PLAYER_FIELD_VENDORBUYBACK_SLOT_1_10 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 10,
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1_11 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 11, PLAYER_FIELD_VENDORBUYBACK_SLOT_1_12 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 12,
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1_13 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 13, PLAYER_FIELD_VENDORBUYBACK_SLOT_1_14 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 14,
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1_15 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 15, PLAYER_FIELD_VENDORBUYBACK_SLOT_1_16 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 16,
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1_17 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 17, PLAYER_FIELD_VENDORBUYBACK_SLOT_1_18 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 18,
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1_19 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 19, PLAYER_FIELD_VENDORBUYBACK_SLOT_1_20 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 20,
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1_21 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 21, PLAYER_FIELD_VENDORBUYBACK_SLOT_1_22 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 22,
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1_23 = PLAYER_FIELD_VENDORBUYBACK_SLOT_1 + 23;

    public const int PLAYER_FIELD_KEYRING_SLOT_1 = B + 0x015C; // Size: 64, Type: LONG, Flags: PRIVATE
    public const int
        PLAYER_FIELD_KEYRING_SLOT_1_1 = PLAYER_FIELD_KEYRING_SLOT_1 + 1, PLAYER_FIELD_KEYRING_SLOT_1_2 = PLAYER_FIELD_KEYRING_SLOT_1 + 2,
        PLAYER_FIELD_KEYRING_SLOT_1_3 = PLAYER_FIELD_KEYRING_SLOT_1 + 3, PLAYER_FIELD_KEYRING_SLOT_1_4 = PLAYER_FIELD_KEYRING_SLOT_1 + 4,
        PLAYER_FIELD_KEYRING_SLOT_1_5 = PLAYER_FIELD_KEYRING_SLOT_1 + 5, PLAYER_FIELD_KEYRING_SLOT_1_6 = PLAYER_FIELD_KEYRING_SLOT_1 + 6,
        PLAYER_FIELD_KEYRING_SLOT_1_7 = PLAYER_FIELD_KEYRING_SLOT_1 + 7, PLAYER_FIELD_KEYRING_SLOT_1_8 = PLAYER_FIELD_KEYRING_SLOT_1 + 8,
        PLAYER_FIELD_KEYRING_SLOT_1_9 = PLAYER_FIELD_KEYRING_SLOT_1 + 9, PLAYER_FIELD_KEYRING_SLOT_1_10 = PLAYER_FIELD_KEYRING_SLOT_1 + 10,
        PLAYER_FIELD_KEYRING_SLOT_1_11 = PLAYER_FIELD_KEYRING_SLOT_1 + 11, PLAYER_FIELD_KEYRING_SLOT_1_12 = PLAYER_FIELD_KEYRING_SLOT_1 + 12,
        PLAYER_FIELD_KEYRING_SLOT_1_13 = PLAYER_FIELD_KEYRING_SLOT_1 + 13, PLAYER_FIELD_KEYRING_SLOT_1_14 = PLAYER_FIELD_KEYRING_SLOT_1 + 14,
        PLAYER_FIELD_KEYRING_SLOT_1_15 = PLAYER_FIELD_KEYRING_SLOT_1 + 15, PLAYER_FIELD_KEYRING_SLOT_1_16 = PLAYER_FIELD_KEYRING_SLOT_1 + 16,
        PLAYER_FIELD_KEYRING_SLOT_1_17 = PLAYER_FIELD_KEYRING_SLOT_1 + 17, PLAYER_FIELD_KEYRING_SLOT_1_18 = PLAYER_FIELD_KEYRING_SLOT_1 + 18,
        PLAYER_FIELD_KEYRING_SLOT_1_19 = PLAYER_FIELD_KEYRING_SLOT_1 + 19, PLAYER_FIELD_KEYRING_SLOT_1_20 = PLAYER_FIELD_KEYRING_SLOT_1 + 20,
        PLAYER_FIELD_KEYRING_SLOT_1_21 = PLAYER_FIELD_KEYRING_SLOT_1 + 21, PLAYER_FIELD_KEYRING_SLOT_1_22 = PLAYER_FIELD_KEYRING_SLOT_1 + 22,
        PLAYER_FIELD_KEYRING_SLOT_1_23 = PLAYER_FIELD_KEYRING_SLOT_1 + 23, PLAYER_FIELD_KEYRING_SLOT_1_24 = PLAYER_FIELD_KEYRING_SLOT_1 + 24,
        PLAYER_FIELD_KEYRING_SLOT_1_25 = PLAYER_FIELD_KEYRING_SLOT_1 + 25, PLAYER_FIELD_KEYRING_SLOT_1_26 = PLAYER_FIELD_KEYRING_SLOT_1 + 26,
        PLAYER_FIELD_KEYRING_SLOT_1_27 = PLAYER_FIELD_KEYRING_SLOT_1 + 27, PLAYER_FIELD_KEYRING_SLOT_1_28 = PLAYER_FIELD_KEYRING_SLOT_1 + 28,
        PLAYER_FIELD_KEYRING_SLOT_1_29 = PLAYER_FIELD_KEYRING_SLOT_1 + 29, PLAYER_FIELD_KEYRING_SLOT_1_30 = PLAYER_FIELD_KEYRING_SLOT_1 + 30,
        PLAYER_FIELD_KEYRING_SLOT_1_31 = PLAYER_FIELD_KEYRING_SLOT_1 + 31, PLAYER_FIELD_KEYRING_SLOT_1_32 = PLAYER_FIELD_KEYRING_SLOT_1 + 32,
        PLAYER_FIELD_KEYRING_SLOT_1_33 = PLAYER_FIELD_KEYRING_SLOT_1 + 33, PLAYER_FIELD_KEYRING_SLOT_1_34 = PLAYER_FIELD_KEYRING_SLOT_1 + 34,
        PLAYER_FIELD_KEYRING_SLOT_1_35 = PLAYER_FIELD_KEYRING_SLOT_1 + 35, PLAYER_FIELD_KEYRING_SLOT_1_36 = PLAYER_FIELD_KEYRING_SLOT_1 + 36,
        PLAYER_FIELD_KEYRING_SLOT_1_37 = PLAYER_FIELD_KEYRING_SLOT_1 + 37, PLAYER_FIELD_KEYRING_SLOT_1_38 = PLAYER_FIELD_KEYRING_SLOT_1 + 38,
        PLAYER_FIELD_KEYRING_SLOT_1_39 = PLAYER_FIELD_KEYRING_SLOT_1 + 39, PLAYER_FIELD_KEYRING_SLOT_1_40 = PLAYER_FIELD_KEYRING_SLOT_1 + 40,
        PLAYER_FIELD_KEYRING_SLOT_1_41 = PLAYER_FIELD_KEYRING_SLOT_1 + 41, PLAYER_FIELD_KEYRING_SLOT_1_42 = PLAYER_FIELD_KEYRING_SLOT_1 + 42,
        PLAYER_FIELD_KEYRING_SLOT_1_43 = PLAYER_FIELD_KEYRING_SLOT_1 + 43, PLAYER_FIELD_KEYRING_SLOT_1_44 = PLAYER_FIELD_KEYRING_SLOT_1 + 44,
        PLAYER_FIELD_KEYRING_SLOT_1_45 = PLAYER_FIELD_KEYRING_SLOT_1 + 45, PLAYER_FIELD_KEYRING_SLOT_1_46 = PLAYER_FIELD_KEYRING_SLOT_1 + 46,
        PLAYER_FIELD_KEYRING_SLOT_1_47 = PLAYER_FIELD_KEYRING_SLOT_1 + 47, PLAYER_FIELD_KEYRING_SLOT_1_48 = PLAYER_FIELD_KEYRING_SLOT_1 + 48,
        PLAYER_FIELD_KEYRING_SLOT_1_49 = PLAYER_FIELD_KEYRING_SLOT_1 + 49, PLAYER_FIELD_KEYRING_SLOT_1_50 = PLAYER_FIELD_KEYRING_SLOT_1 + 50,
        PLAYER_FIELD_KEYRING_SLOT_1_51 = PLAYER_FIELD_KEYRING_SLOT_1 + 51, PLAYER_FIELD_KEYRING_SLOT_1_52 = PLAYER_FIELD_KEYRING_SLOT_1 + 52,
        PLAYER_FIELD_KEYRING_SLOT_1_53 = PLAYER_FIELD_KEYRING_SLOT_1 + 53, PLAYER_FIELD_KEYRING_SLOT_1_54 = PLAYER_FIELD_KEYRING_SLOT_1 + 54,
        PLAYER_FIELD_KEYRING_SLOT_1_55 = PLAYER_FIELD_KEYRING_SLOT_1 + 55, PLAYER_FIELD_KEYRING_SLOT_1_56 = PLAYER_FIELD_KEYRING_SLOT_1 + 56,
        PLAYER_FIELD_KEYRING_SLOT_1_57 = PLAYER_FIELD_KEYRING_SLOT_1 + 57, PLAYER_FIELD_KEYRING_SLOT_1_58 = PLAYER_FIELD_KEYRING_SLOT_1 + 58,
        PLAYER_FIELD_KEYRING_SLOT_1_59 = PLAYER_FIELD_KEYRING_SLOT_1 + 59, PLAYER_FIELD_KEYRING_SLOT_1_60 = PLAYER_FIELD_KEYRING_SLOT_1 + 60,
        PLAYER_FIELD_KEYRING_SLOT_1_61 = PLAYER_FIELD_KEYRING_SLOT_1 + 61, PLAYER_FIELD_KEYRING_SLOT_1_62 = PLAYER_FIELD_KEYRING_SLOT_1 + 62,
        PLAYER_FIELD_KEYRING_SLOT_1_63 = PLAYER_FIELD_KEYRING_SLOT_1 + 63;

    public const int PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 = B + 0x019C; // Size: 64, Type: LONG, Flags: PRIVATE
    public const int
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_1 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 1, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_2 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 2,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_3 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 3, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_4 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 4,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_5 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 5, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_6 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 6,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_7 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 7, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_8 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 8,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_9 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 9, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_10 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 10,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_11 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 11, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_12 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 12,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_13 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 13, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_14 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 14,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_15 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 15, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_16 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 16,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_17 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 17, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_18 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 18,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_19 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 19, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_20 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 20,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_21 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 21, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_22 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 22,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_23 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 23, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_24 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 24,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_25 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 25, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_26 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 26,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_27 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 27, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_28 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 28,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_29 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 29, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_30 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 30,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_31 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 31, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_32 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 32,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_33 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 33, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_34 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 34,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_35 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 35, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_36 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 36,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_37 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 37, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_38 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 38,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_39 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 39, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_40 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 40,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_41 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 41, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_42 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 42,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_43 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 43, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_44 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 44,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_45 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 45, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_46 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 46,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_47 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 47, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_48 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 48,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_49 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 49, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_50 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 50,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_51 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 51, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_52 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 52,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_53 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 53, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_54 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 54,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_55 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 55, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_56 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 56,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_57 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 57, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_58 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 58,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_59 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 59, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_60 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 60,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_61 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 61, PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_62 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 62,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1_63 = PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 + 63;

    public const int PLAYER_FARSIGHT               = B + 0x01DC; // Size: 2, Type: LONG, Flags: PRIVATE
    public const int PLAYER__FIELD_KNOWN_TITLES    = B + 0x01DE; // Size: 2, Type: LONG, Flags: PRIVATE
    public const int PLAYER__FIELD_KNOWN_TITLES1   = B + 0x01E0; // Size: 2, Type: LONG, Flags: PRIVATE
    public const int PLAYER__FIELD_KNOWN_TITLES2   = B + 0x01E2; // Size: 2, Type: LONG, Flags: PRIVATE
    public const int PLAYER_FIELD_KNOWN_CURRENCIES = B + 0x01E4; // Size: 2, Type: LONG, Flags: PRIVATE
    public const int PLAYER_XP                     = B + 0x01E6; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_NEXT_LEVEL_XP          = B + 0x01E7; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_SKILL_INFO_1_1         = B + 0x01E8; // Size: 384, Type: TWO_SHORT, Flags: PRIVATE
    public const int PLAYER_CHARACTER_POINTS1      = B + 0x0368; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_CHARACTER_POINTS2      = B + 0x0369; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_TRACK_CREATURES        = B + 0x036A; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_TRACK_RESOURCES        = B + 0x036B; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_BLOCK_PERCENTAGE       = B + 0x036C; // Size: 1, Type: FLOAT, Flags: PRIVATE
    public const int PLAYER_DODGE_PERCENTAGE       = B + 0x036D; // Size: 1, Type: FLOAT, Flags: PRIVATE
    public const int PLAYER_PARRY_PERCENTAGE       = B + 0x036E; // Size: 1, Type: FLOAT, Flags: PRIVATE
    public const int PLAYER_EXPERTISE              = B + 0x036F; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_OFFHAND_EXPERTISE      = B + 0x0370; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_CRIT_PERCENTAGE        = B + 0x0371; // Size: 1, Type: FLOAT, Flags: PRIVATE
    public const int PLAYER_RANGED_CRIT_PERCENTAGE = B + 0x0372; // Size: 1, Type: FLOAT, Flags: PRIVATE
    public const int PLAYER_OFFHAND_CRIT_PERCENTAGE = B + 0x0373; // Size: 1, Type: FLOAT, Flags: PRIVATE
    public const int PLAYER_SPELL_CRIT_PERCENTAGE1   = B + 0x0374; // Size: 7, Type: FLOAT, Flags: PRIVATE
    public const int PLAYER_SPELL_CRIT_PERCENTAGE1_1 = B + 0x0375;
    public const int PLAYER_SPELL_CRIT_PERCENTAGE1_2 = B + 0x0376;
    public const int PLAYER_SPELL_CRIT_PERCENTAGE1_3 = B + 0x0377;
    public const int PLAYER_SPELL_CRIT_PERCENTAGE1_4 = B + 0x0378;
    public const int PLAYER_SPELL_CRIT_PERCENTAGE1_5 = B + 0x0379;
    public const int PLAYER_SPELL_CRIT_PERCENTAGE1_6 = B + 0x037A;
    public const int PLAYER_SHIELD_BLOCK           = B + 0x037B; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_SHIELD_BLOCK_CRIT_PERCENTAGE = B + 0x037C; // Size: 1, Type: FLOAT, Flags: PRIVATE
    public const int PLAYER_EXPLORED_ZONES_1       = B + 0x037D; // Size: 128, Type: BYTES, Flags: PRIVATE
    public const int PLAYER_REST_STATE_EXPERIENCE  = B + 0x03FD; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_COINAGE          = B + 0x03FE; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_POS   = B + 0x03FF; // Size: 7, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_POS_1 = B + 0x0400;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_POS_2 = B + 0x0401;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_POS_3 = B + 0x0402;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_POS_4 = B + 0x0403;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_POS_5 = B + 0x0404;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_POS_6 = B + 0x0405;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_NEG   = B + 0x0406; // Size: 7, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_NEG_1 = B + 0x0407;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_NEG_2 = B + 0x0408;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_NEG_3 = B + 0x0409;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_NEG_4 = B + 0x040A;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_NEG_5 = B + 0x040B;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_NEG_6 = B + 0x040C;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_PCT   = B + 0x040D; // Size: 7, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_PCT_1 = B + 0x040E;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_PCT_2 = B + 0x040F;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_PCT_3 = B + 0x0410;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_PCT_4 = B + 0x0411;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_PCT_5 = B + 0x0412;
    public const int PLAYER_FIELD_MOD_DAMAGE_DONE_PCT_6 = B + 0x0413;
    public const int PLAYER_FIELD_MOD_HEALING_DONE_POS  = B + 0x0414; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_MOD_HEALING_PCT       = B + 0x0415; // Size: 1, Type: FLOAT, Flags: PRIVATE
    public const int PLAYER_FIELD_MOD_HEALING_DONE_PCT  = B + 0x0416; // Size: 1, Type: FLOAT, Flags: PRIVATE
    public const int PLAYER_FIELD_MOD_TARGET_RESISTANCE = B + 0x0417; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE = B + 0x0418; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_BYTES            = B + 0x0419; // Size: 1, Type: BYTES, Flags: PRIVATE
    public const int PLAYER_AMMO_ID                = B + 0x041A; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_SELF_RES_SPELL         = B + 0x041B; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_PVP_MEDALS       = B + 0x041C; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_BUYBACK_PRICE_1  = B + 0x041D; // Size: 12, Type: INT, Flags: PRIVATE
    public const int
        PLAYER_FIELD_BUYBACK_PRICE_1_1 = PLAYER_FIELD_BUYBACK_PRICE_1 + 1, PLAYER_FIELD_BUYBACK_PRICE_1_2 = PLAYER_FIELD_BUYBACK_PRICE_1 + 2,
        PLAYER_FIELD_BUYBACK_PRICE_1_3 = PLAYER_FIELD_BUYBACK_PRICE_1 + 3, PLAYER_FIELD_BUYBACK_PRICE_1_4 = PLAYER_FIELD_BUYBACK_PRICE_1 + 4,
        PLAYER_FIELD_BUYBACK_PRICE_1_5 = PLAYER_FIELD_BUYBACK_PRICE_1 + 5, PLAYER_FIELD_BUYBACK_PRICE_1_6 = PLAYER_FIELD_BUYBACK_PRICE_1 + 6,
        PLAYER_FIELD_BUYBACK_PRICE_1_7 = PLAYER_FIELD_BUYBACK_PRICE_1 + 7, PLAYER_FIELD_BUYBACK_PRICE_1_8 = PLAYER_FIELD_BUYBACK_PRICE_1 + 8,
        PLAYER_FIELD_BUYBACK_PRICE_1_9 = PLAYER_FIELD_BUYBACK_PRICE_1 + 9, PLAYER_FIELD_BUYBACK_PRICE_1_10 = PLAYER_FIELD_BUYBACK_PRICE_1 + 10,
        PLAYER_FIELD_BUYBACK_PRICE_1_11 = PLAYER_FIELD_BUYBACK_PRICE_1 + 11;
    public const int PLAYER_FIELD_BUYBACK_TIMESTAMP_1 = B + 0x0429; // Size: 12, Type: INT, Flags: PRIVATE
    public const int
        PLAYER_FIELD_BUYBACK_TIMESTAMP_1_1 = PLAYER_FIELD_BUYBACK_TIMESTAMP_1 + 1, PLAYER_FIELD_BUYBACK_TIMESTAMP_1_2 = PLAYER_FIELD_BUYBACK_TIMESTAMP_1 + 2,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_1_3 = PLAYER_FIELD_BUYBACK_TIMESTAMP_1 + 3, PLAYER_FIELD_BUYBACK_TIMESTAMP_1_4 = PLAYER_FIELD_BUYBACK_TIMESTAMP_1 + 4,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_1_5 = PLAYER_FIELD_BUYBACK_TIMESTAMP_1 + 5, PLAYER_FIELD_BUYBACK_TIMESTAMP_1_6 = PLAYER_FIELD_BUYBACK_TIMESTAMP_1 + 6,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_1_7 = PLAYER_FIELD_BUYBACK_TIMESTAMP_1 + 7, PLAYER_FIELD_BUYBACK_TIMESTAMP_1_8 = PLAYER_FIELD_BUYBACK_TIMESTAMP_1 + 8,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_1_9 = PLAYER_FIELD_BUYBACK_TIMESTAMP_1 + 9, PLAYER_FIELD_BUYBACK_TIMESTAMP_1_10 = PLAYER_FIELD_BUYBACK_TIMESTAMP_1 + 10,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_1_11 = PLAYER_FIELD_BUYBACK_TIMESTAMP_1 + 11;
    public const int PLAYER_FIELD_KILLS            = B + 0x0435; // Size: 1, Type: TWO_SHORT, Flags: PRIVATE
    public const int PLAYER_FIELD_TODAY_CONTRIBUTION = B + 0x0436; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_YESTERDAY_CONTRIBUTION = B + 0x0437; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_LIFETIME_HONORBALE_KILLS = B + 0x0438; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_BYTES2           = B + 0x0439; // Size: 1, Type: 6, Flags: PRIVATE
    public const int PLAYER_FIELD_WATCHED_FACTION_INDEX = B + 0x043A; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_COMBAT_RATING_1  = B + 0x043B; // Size: 25, Type: INT, Flags: PRIVATE
    public const int
        PLAYER_FIELD_COMBAT_RATING_1_1 = PLAYER_FIELD_COMBAT_RATING_1 + 1, PLAYER_FIELD_COMBAT_RATING_1_2 = PLAYER_FIELD_COMBAT_RATING_1 + 2,
        PLAYER_FIELD_COMBAT_RATING_1_3 = PLAYER_FIELD_COMBAT_RATING_1 + 3, PLAYER_FIELD_COMBAT_RATING_1_4 = PLAYER_FIELD_COMBAT_RATING_1 + 4,
        PLAYER_FIELD_COMBAT_RATING_1_5 = PLAYER_FIELD_COMBAT_RATING_1 + 5, PLAYER_FIELD_COMBAT_RATING_1_6 = PLAYER_FIELD_COMBAT_RATING_1 + 6,
        PLAYER_FIELD_COMBAT_RATING_1_7 = PLAYER_FIELD_COMBAT_RATING_1 + 7, PLAYER_FIELD_COMBAT_RATING_1_8 = PLAYER_FIELD_COMBAT_RATING_1 + 8,
        PLAYER_FIELD_COMBAT_RATING_1_9 = PLAYER_FIELD_COMBAT_RATING_1 + 9, PLAYER_FIELD_COMBAT_RATING_1_10 = PLAYER_FIELD_COMBAT_RATING_1 + 10,
        PLAYER_FIELD_COMBAT_RATING_1_11 = PLAYER_FIELD_COMBAT_RATING_1 + 11, PLAYER_FIELD_COMBAT_RATING_1_12 = PLAYER_FIELD_COMBAT_RATING_1 + 12,
        PLAYER_FIELD_COMBAT_RATING_1_13 = PLAYER_FIELD_COMBAT_RATING_1 + 13, PLAYER_FIELD_COMBAT_RATING_1_14 = PLAYER_FIELD_COMBAT_RATING_1 + 14,
        PLAYER_FIELD_COMBAT_RATING_1_15 = PLAYER_FIELD_COMBAT_RATING_1 + 15, PLAYER_FIELD_COMBAT_RATING_1_16 = PLAYER_FIELD_COMBAT_RATING_1 + 16,
        PLAYER_FIELD_COMBAT_RATING_1_17 = PLAYER_FIELD_COMBAT_RATING_1 + 17, PLAYER_FIELD_COMBAT_RATING_1_18 = PLAYER_FIELD_COMBAT_RATING_1 + 18,
        PLAYER_FIELD_COMBAT_RATING_1_19 = PLAYER_FIELD_COMBAT_RATING_1 + 19, PLAYER_FIELD_COMBAT_RATING_1_20 = PLAYER_FIELD_COMBAT_RATING_1 + 20,
        PLAYER_FIELD_COMBAT_RATING_1_21 = PLAYER_FIELD_COMBAT_RATING_1 + 21, PLAYER_FIELD_COMBAT_RATING_1_22 = PLAYER_FIELD_COMBAT_RATING_1 + 22,
        PLAYER_FIELD_COMBAT_RATING_1_23 = PLAYER_FIELD_COMBAT_RATING_1 + 23, PLAYER_FIELD_COMBAT_RATING_1_24 = PLAYER_FIELD_COMBAT_RATING_1 + 24;

    // Équipes d'arène : 2vs2 (_1_1 à _1_1_6), 3vs3 (_1_1_7 à _1_1_13), 5vs5 (_1_1_14 à _1_1_20).
    public const int PLAYER_FIELD_ARENA_TEAM_INFO_1_1 = B + 0x0454; // Size: 21, Type: INT, Flags: PRIVATE
    public const int
        PLAYER_FIELD_ARENA_TEAM_INFO_1_1_1 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 1, PLAYER_FIELD_ARENA_TEAM_INFO_1_1_2 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 2,
        PLAYER_FIELD_ARENA_TEAM_INFO_1_1_3 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 3, PLAYER_FIELD_ARENA_TEAM_INFO_1_1_4 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 4,
        PLAYER_FIELD_ARENA_TEAM_INFO_1_1_5 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 5, PLAYER_FIELD_ARENA_TEAM_INFO_1_1_6 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 6,
        PLAYER_FIELD_ARENA_TEAM_INFO_1_1_7 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 7, PLAYER_FIELD_ARENA_TEAM_INFO_1_1_8 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 8,
        PLAYER_FIELD_ARENA_TEAM_INFO_1_1_9 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 9, PLAYER_FIELD_ARENA_TEAM_INFO_1_1_10 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 10,
        PLAYER_FIELD_ARENA_TEAM_INFO_1_1_11 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 11, PLAYER_FIELD_ARENA_TEAM_INFO_1_1_12 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 12,
        PLAYER_FIELD_ARENA_TEAM_INFO_1_1_13 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 13, PLAYER_FIELD_ARENA_TEAM_INFO_1_1_14 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 14,
        PLAYER_FIELD_ARENA_TEAM_INFO_1_1_15 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 15, PLAYER_FIELD_ARENA_TEAM_INFO_1_1_16 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 16,
        PLAYER_FIELD_ARENA_TEAM_INFO_1_1_17 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 17, PLAYER_FIELD_ARENA_TEAM_INFO_1_1_18 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 18,
        PLAYER_FIELD_ARENA_TEAM_INFO_1_1_19 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 19, PLAYER_FIELD_ARENA_TEAM_INFO_1_1_20 = PLAYER_FIELD_ARENA_TEAM_INFO_1_1 + 20;

    public const int PLAYER_FIELD_HONOR_CURRENCY   = B + 0x0469; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_ARENA_CURRENCY   = B + 0x046A; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_MAX_LEVEL        = B + 0x046B; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_DAILY_QUESTS_1   = B + 0x046C; // Size: 25, Type: INT, Flags: PRIVATE
    public const int
        PLAYER_FIELD_DAILY_QUESTS_1_1 = PLAYER_FIELD_DAILY_QUESTS_1 + 1, PLAYER_FIELD_DAILY_QUESTS_1_2 = PLAYER_FIELD_DAILY_QUESTS_1 + 2,
        PLAYER_FIELD_DAILY_QUESTS_1_3 = PLAYER_FIELD_DAILY_QUESTS_1 + 3, PLAYER_FIELD_DAILY_QUESTS_1_4 = PLAYER_FIELD_DAILY_QUESTS_1 + 4,
        PLAYER_FIELD_DAILY_QUESTS_1_5 = PLAYER_FIELD_DAILY_QUESTS_1 + 5, PLAYER_FIELD_DAILY_QUESTS_1_6 = PLAYER_FIELD_DAILY_QUESTS_1 + 6,
        PLAYER_FIELD_DAILY_QUESTS_1_7 = PLAYER_FIELD_DAILY_QUESTS_1 + 7, PLAYER_FIELD_DAILY_QUESTS_1_8 = PLAYER_FIELD_DAILY_QUESTS_1 + 8,
        PLAYER_FIELD_DAILY_QUESTS_1_9 = PLAYER_FIELD_DAILY_QUESTS_1 + 9, PLAYER_FIELD_DAILY_QUESTS_1_10 = PLAYER_FIELD_DAILY_QUESTS_1 + 10,
        PLAYER_FIELD_DAILY_QUESTS_1_11 = PLAYER_FIELD_DAILY_QUESTS_1 + 11, PLAYER_FIELD_DAILY_QUESTS_1_12 = PLAYER_FIELD_DAILY_QUESTS_1 + 12,
        PLAYER_FIELD_DAILY_QUESTS_1_13 = PLAYER_FIELD_DAILY_QUESTS_1 + 13, PLAYER_FIELD_DAILY_QUESTS_1_14 = PLAYER_FIELD_DAILY_QUESTS_1 + 14,
        PLAYER_FIELD_DAILY_QUESTS_1_15 = PLAYER_FIELD_DAILY_QUESTS_1 + 15, PLAYER_FIELD_DAILY_QUESTS_1_16 = PLAYER_FIELD_DAILY_QUESTS_1 + 16,
        PLAYER_FIELD_DAILY_QUESTS_1_17 = PLAYER_FIELD_DAILY_QUESTS_1 + 17, PLAYER_FIELD_DAILY_QUESTS_1_18 = PLAYER_FIELD_DAILY_QUESTS_1 + 18,
        PLAYER_FIELD_DAILY_QUESTS_1_19 = PLAYER_FIELD_DAILY_QUESTS_1 + 19, PLAYER_FIELD_DAILY_QUESTS_1_20 = PLAYER_FIELD_DAILY_QUESTS_1 + 20,
        PLAYER_FIELD_DAILY_QUESTS_1_21 = PLAYER_FIELD_DAILY_QUESTS_1 + 21, PLAYER_FIELD_DAILY_QUESTS_1_22 = PLAYER_FIELD_DAILY_QUESTS_1 + 22,
        PLAYER_FIELD_DAILY_QUESTS_1_23 = PLAYER_FIELD_DAILY_QUESTS_1 + 23, PLAYER_FIELD_DAILY_QUESTS_1_24 = PLAYER_FIELD_DAILY_QUESTS_1 + 24;
    public const int PLAYER_RUNE_REGEN_1           = B + 0x0485; // Size: 4, Type: FLOAT, Flags: PRIVATE
    public const int PLAYER_RUNE_REGEN_1_1         = B + 0x0486;
    public const int PLAYER_RUNE_REGEN_1_2         = B + 0x0487;
    public const int PLAYER_RUNE_REGEN_1_3         = B + 0x0488;
    public const int PLAYER_NO_REAGENT_COST_1      = B + 0x0489; // Size: 3, Type: INT, Flags: PRIVATE
    public const int PLAYER_NO_REAGENT_COST_1_1    = B + 0x048A;
    public const int PLAYER_NO_REAGENT_COST_1_2    = B + 0x048B;
    public const int PLAYER_FIELD_GLYPH_SLOTS_1    = B + 0x048C; // Size: 6, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_GLYPH_SLOTS_1_1  = B + 0x048D;
    public const int PLAYER_FIELD_GLYPH_SLOTS_1_2  = B + 0x048E;
    public const int PLAYER_FIELD_GLYPH_SLOTS_1_3  = B + 0x048F;
    public const int PLAYER_FIELD_GLYPH_SLOTS_1_4  = B + 0x0490;
    public const int PLAYER_FIELD_GLYPH_SLOTS_1_5  = B + 0x0491;
    public const int PLAYER_FIELD_GLYPHS_1         = B + 0x0492; // Size: 6, Type: INT, Flags: PRIVATE
    public const int PLAYER_FIELD_GLYPHS_1_1       = B + 0x0493;
    public const int PLAYER_FIELD_GLYPHS_1_2       = B + 0x0494;
    public const int PLAYER_FIELD_GLYPHS_1_3       = B + 0x0495;
    public const int PLAYER_FIELD_GLYPHS_1_4       = B + 0x0496;
    public const int PLAYER_FIELD_GLYPHS_1_5       = B + 0x0497;
    public const int PLAYER_GLYPHS_ENABLED         = B + 0x0498; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_PET_SPELL_POWER        = B + 0x0499; // Size: 1, Type: INT, Flags: PRIVATE
    public const int PLAYER_END                    = B + 0x049A;

    // Champs manuels (#define C++)
    public const int PLAYER_VISIBLE_ITEM_LENGTH = 2;   // ENTRYID + ENCHANTMENT
    public const int PLAYER_VISIBLE_ITEM_MAX    = 19;  // index 0 à 18 (_1 à _19)
    public const int PLAYER_EXPLORED_ZONES_MAX  = 128;
    public const int PLAYER_QUEST_LOG_MAX       = 25;
    public const int PLAYER_QUEST_SLOT_MAX      = 5;   // 5 DWORD par entrée du journal
}

public static class EGameObjectFields
{
    private const int B = EObjectFields.OBJECT_END;

    public const int OBJECT_FIELD_CREATED_BY      = B + 0x0000; // Size: 2, Type: LONG, Flags: PUBLIC
    public const int GAMEOBJECT_DISPLAYID         = B + 0x0002; // Size: 1, Type: INT, Flags: PUBLIC
    public const int GAMEOBJECT_FLAGS             = B + 0x0003; // Size: 1, Type: INT, Flags: PUBLIC
    public const int GAMEOBJECT_PARENTROTATION    = B + 0x0004; // Size: 4, Type: FLOAT, Flags: PUBLIC
    public const int GAMEOBJECT_PARENTROTATION_1  = B + 0x0005;
    public const int GAMEOBJECT_PARENTROTATION_2  = B + 0x0006;
    public const int GAMEOBJECT_PARENTROTATION_3  = B + 0x0007;
    public const int GAMEOBJECT_DYNAMIC           = B + 0x0008; // Size: 1, Type: TWO_SHORT, Flags: DYNAMIC
    public const int GAMEOBJECT_FACTION           = B + 0x0009; // Size: 1, Type: INT, Flags: PUBLIC
    public const int GAMEOBJECT_LEVEL             = B + 0x000A; // Size: 1, Type: INT, Flags: PUBLIC
    public const int GAMEOBJECT_BYTES_1           = B + 0x000B; // Size: 1, Type: BYTES, Flags: PUBLIC — [3]:animprogress [2]:artkit [1]:type [0]:state
    public const int GAMEOBJECT_END               = B + 0x000C;
}

public static class EDynamicObjectFields
{
    private const int B = EObjectFields.OBJECT_END;

    public const int DYNAMICOBJECT_CASTER   = B + 0x0000; // Size: 2, Type: LONG, Flags: PUBLIC
    public const int DYNAMICOBJECT_BYTES    = B + 0x0002; // Size: 1, Type: BYTES, Flags: PUBLIC
    public const int DYNAMICOBJECT_SPELLID  = B + 0x0003; // Size: 1, Type: INT, Flags: PUBLIC
    public const int DYNAMICOBJECT_RADIUS   = B + 0x0004; // Size: 1, Type: FLOAT, Flags: PUBLIC
    public const int DYNAMICOBJECT_CASTTIME = B + 0x0005; // Size: 1, Type: INT, Flags: PUBLIC
    public const int DYNAMICOBJECT_END      = B + 0x0006;
}

public static class ECorpseFields
{
    private const int B = EObjectFields.OBJECT_END;

    public const int CORPSE_FIELD_OWNER      = B + 0x0000; // Size: 2, Type: LONG, Flags: PUBLIC
    public const int CORPSE_FIELD_PARTY      = B + 0x0002; // Size: 2, Type: LONG, Flags: PUBLIC
    public const int CORPSE_FIELD_DISPLAY_ID = B + 0x0004; // Size: 1, Type: INT, Flags: PUBLIC
    public const int CORPSE_FIELD_ITEM       = B + 0x0005; // Size: 19, Type: INT, Flags: PUBLIC
    public const int
        CORPSE_FIELD_ITEM_1 = CORPSE_FIELD_ITEM + 1, CORPSE_FIELD_ITEM_2 = CORPSE_FIELD_ITEM + 2,
        CORPSE_FIELD_ITEM_3 = CORPSE_FIELD_ITEM + 3, CORPSE_FIELD_ITEM_4 = CORPSE_FIELD_ITEM + 4,
        CORPSE_FIELD_ITEM_5 = CORPSE_FIELD_ITEM + 5, CORPSE_FIELD_ITEM_6 = CORPSE_FIELD_ITEM + 6,
        CORPSE_FIELD_ITEM_7 = CORPSE_FIELD_ITEM + 7, CORPSE_FIELD_ITEM_8 = CORPSE_FIELD_ITEM + 8,
        CORPSE_FIELD_ITEM_9 = CORPSE_FIELD_ITEM + 9, CORPSE_FIELD_ITEM_10 = CORPSE_FIELD_ITEM + 10,
        CORPSE_FIELD_ITEM_11 = CORPSE_FIELD_ITEM + 11, CORPSE_FIELD_ITEM_12 = CORPSE_FIELD_ITEM + 12,
        CORPSE_FIELD_ITEM_13 = CORPSE_FIELD_ITEM + 13, CORPSE_FIELD_ITEM_14 = CORPSE_FIELD_ITEM + 14,
        CORPSE_FIELD_ITEM_15 = CORPSE_FIELD_ITEM + 15, CORPSE_FIELD_ITEM_16 = CORPSE_FIELD_ITEM + 16,
        CORPSE_FIELD_ITEM_17 = CORPSE_FIELD_ITEM + 17, CORPSE_FIELD_ITEM_18 = CORPSE_FIELD_ITEM + 18;
    public const int CORPSE_FIELD_BYTES_1       = B + 0x0018; // Size: 1, Type: BYTES, Flags: PUBLIC
    public const int CORPSE_FIELD_BYTES_2       = B + 0x0019; // Size: 1, Type: BYTES, Flags: PUBLIC
    public const int CORPSE_FIELD_GUILD         = B + 0x001A; // Size: 1, Type: INT, Flags: PUBLIC
    public const int CORPSE_FIELD_FLAGS         = B + 0x001B; // Size: 1, Type: INT, Flags: PUBLIC
    public const int CORPSE_FIELD_DYNAMIC_FLAGS = B + 0x001C; // Size: 1, Type: INT, Flags: DYNAMIC
    public const int CORPSE_FIELD_PAD           = B + 0x001D; // Size: 1, Type: INT, Flags: NONE
    public const int CORPSE_END                 = B + 0x001E;
}
