/*
 * Wow Arbonne Ascent Development MMORPG Server
 * Copyright (C) 2007-2025 WAAD Team <https://arbonne.games-rpg.net/>
 *
 * From original Ascent MMORPG Server, 2005-2008, which doesn't exist anymore.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

namespace WaadShared.AuthCodes;

public enum LoginErrorCode
{
    RESPONSE_SUCCESS = 0x00,
    RESPONSE_FAILURE = 0x01,
    RESPONSE_CANCELLED = 0x02,
    RESPONSE_DISCONNECTED = 0x03,
    RESPONSE_FAILED_TO_CONNECT = 0x04,
    RESPONSE_CONNECTED = 0x05,
    RESPONSE_VERSION_MISMATCH = 0x06,

    CSTATUS_CONNECTING = 0x07,
    CSTATUS_NEGOTIATING_SECURITY = 0x08,
    CSTATUS_NEGOTIATION_COMPLETE = 0x09,
    CSTATUS_NEGOTIATION_FAILED = 0x0A,
    CSTATUS_AUTHENTICATING = 0x0B,

    AUTH_OK = 0x0C,
    AUTH_FAILED = 0x0D,
    AUTH_REJECT = 0x0E,
    AUTH_BAD_SERVER_PROOF = 0x0F,
    AUTH_UNAVAILABLE = 0x10,
    AUTH_SYSTEM_ERROR = 0x11,
    AUTH_BILLING_ERROR = 0x12,
    AUTH_BILLING_EXPIRED = 0x13,
    AUTH_VERSION_MISMATCH = 0x14,
    AUTH_UNKNOWN_ACCOUNT = 0x15,
    AUTH_INCORRECT_PASSWORD = 0x16,
    AUTH_SESSION_EXPIRED = 0x17,
    AUTH_SERVER_SHUTTING_DOWN = 0x18,
    AUTH_ALREADY_LOGGING_IN = 0x19,
    AUTH_LOGIN_SERVER_NOT_FOUND = 0x1A,
    AUTH_WAIT_QUEUE = 0x1B,
    AUTH_BANNED = 0x1C,
    AUTH_ALREADY_ONLINE = 0x1D,
    AUTH_NO_TIME = 0x1E,
    AUTH_DB_BUSY = 0x1F,
    AUTH_SUSPENDED = 0x20,
    AUTH_PARENTAL_CONTROL = 0x21,
    AUTH_LOCKED_ENFORCED = 0x22,

    REALM_LIST_IN_PROGRESS = 0x23,
    REALM_LIST_SUCCESS = 0x24,
    REALM_LIST_FAILED = 0x25,
    REALM_LIST_INVALID = 0x26,
    REALM_LIST_REALM_NOT_FOUND = 0x27,

    ACCOUNT_CREATE_IN_PROGRESS = 0x28,
    ACCOUNT_CREATE_SUCCESS = 0x29,
    ACCOUNT_CREATE_FAILED = 0x2A,

    CHAR_LIST_RETRIEVING = 0x2B,
    CHAR_LIST_RETRIEVED = 0x2C,
    CHAR_LIST_FAILED = 0x2D,

    CHAR_CREATE_IN_PROGRESS = 0x2E,
    CHAR_CREATE_SUCCESS = 0x2F,
    CHAR_CREATE_ERROR = 0x30,
    CHAR_CREATE_FAILED = 0x31,
    CHAR_CREATE_NAME_IN_USE = 0x32,
    CHAR_CREATE_DISABLED = 0x33,
    CHAR_CREATE_PVP_TEAMS_VIOLATION = 0x34,
    CHAR_CREATE_SERVER_LIMIT = 0x35,
    CHAR_CREATE_ACCOUNT_LIMIT = 0x36,
    CHAR_CREATE_SERVER_QUEUE = 0x37,
    CHAR_CREATE_ONLY_EXISTING = 0x38,
    CHAR_CREATE_EXPANSION = 0x39,
    CHAR_CREATE_EXPANSION_CLASS = 0x3A,
    CHAR_CREATE_LEVEL_REQUIREMENT = 0x3B,
    CHAR_CREATE_UNIQUE_CLASS_LIMIT = 0x3C,
    CHAR_CREATE_CHARACTER_IN_GUILD = 0x3D,
    CHAR_CREATE_RESTRICTED_RACECLASS = 0x3E,
    CHAR_CREATE_CHARACTER_CHOOSE_RACE = 0x3F,
    CHAR_CREATE_CHARACTER_ARENA_LEADER = 0x40,
    CHAR_CREATE_CHARACTER_DELETE_MAIL = 0x41,
    CHAR_CREATE_CHARACTER_SWAP_FACTION = 0x42,
    CHAR_CREATE_CHARACTER_RACE_ONLY = 0x43,
    CHAR_CREATE_CHARACTER_GOLD_LIMIT = 0x44,
    CHAR_CREATE_FORCE_LOGIN = 0x45,

    CHAR_DELETE_IN_PROGRESS = 0x46,
    CHAR_DELETE_SUCCESS = 0x47,
    CHAR_DELETE_FAILED = 0x48,
    CHAR_DELETE_FAILED_LOCKED_FOR_TRANSFER = 0x49,
    CHAR_DELETE_FAILED_GUILD_LEADER = 0x4A,
    CHAR_DELETE_FAILED_ARENA_CAPTAIN = 0x4B,

    CHAR_LOGIN_IN_PROGRESS = 0x4C,
    CHAR_LOGIN_SUCCESS = 0x4D,
    CHAR_LOGIN_NO_WORLD = 0x4E,
    CHAR_LOGIN_DUPLICATE_CHARACTER = 0x4F,
    CHAR_LOGIN_NO_INSTANCES = 0x50,
    CHAR_LOGIN_FAILED = 0x51,
    CHAR_LOGIN_DISABLED = 0x52,
    CHAR_LOGIN_NO_CHARACTER = 0x53,
    CHAR_LOGIN_LOCKED_FOR_TRANSFER = 0x54,
    CHAR_LOGIN_LOCKED_BY_BILLING = 0x55,
    CHAR_LOGIN_LOCKED_BY_MOBILE_AH = 0x56,

    CHAR_NAME_SUCCESS = 0x57,
    CHAR_NAME_FAILURE = 0x58,
    CHAR_NAME_NO_NAME = 0x59,
    CHAR_NAME_TOO_SHORT = 0x5A,
    CHAR_NAME_TOO_LONG = 0x5B,
    CHAR_NAME_INVALID_CHARACTER = 0x5C,
    CHAR_NAME_MIXED_LANGUAGES = 0x5D,
    CHAR_NAME_PROFANE = 0x5E,
    CHAR_NAME_RESERVED = 0x5F,
    CHAR_NAME_INVALID_APOSTROPHE = 0x60,
    CHAR_NAME_MULTIPLE_APOSTROPHES = 0x61,
    CHAR_NAME_THREE_CONSECUTIVE = 0x62,
    CHAR_NAME_INVALID_SPACE = 0x63,
    CHAR_NAME_CONSECUTIVE_SPACES = 0x64,
    CHAR_NAME_RUSSIAN_CONSECUTIVE_SILENT_CHARACTERS = 0x65,
    CHAR_NAME_RUSSIAN_SILENT_CHARACTER_AT_BEGINNING_OR_END = 0x66,
    CHAR_NAME_DECLENSION_DOESNT_MATCH_BASE_NAME = 0x67,
}

public enum LoginStatusCode
{
    LOGIN_OK = 0x00,
    LOGIN_INVALID_CHALLENGE_MESSAGE = 0x01,
    LOGIN_SRP_ERROR = 0x02,
    LOGIN_INVALID_PROOF_MESSAGE = 0x03,
    LOGIN_BAD_SERVER_PROOF = 0x04,
    LOGIN_INVALID_RECODE_MESSAGE = 0x05,
    LOGIN_BAD_SERVER_RECODE_PROOF = 0x06,
    LOGIN_UNKNOWN_ACCOUNT = 0x07,
    LOGIN_UNKNOWN_ACCOUNT_PIN = 0x08,
    LOGIN_UNKNOWN_ACCOUNT_CALL = 0x09,
    LOGIN_INCORRECT_PASSWORD = 0x0A,
    LOGIN_FAILED = 0x0B,
    LOGIN_SERVER_DOWN = 0x0C,
    LOGIN_BANNED = 0x0D,
    LOGIN_BADVERSION = 0x0E,
    LOGIN_ALREADYONLINE = 0x0F,
    LOGIN_NOTIME = 0x10,
    LOGIN_DBBUSY = 0x11,
    LOGIN_SUSPENDED = 0x12,
    LOGIN_PARENTALCONTROL = 0x13,
    LOGIN_LOCKED_ENFORCED = 0x14,
    DISCONNECTED = 0x15,
    LOGIN_ACCOUNT_CONVERTED = 0x16,
    LOGIN_ANTI_INDULGENCE = 0x17,
    LOGIN_EXPIRED = 0x18,
    LOGIN_TRIAL_EXPIRED = 0x19,
    LOGIN_NO_GAME_ACCOUNT = 0x1A,
    LOGIN_AUTH_OUTAGE = 0x1B,
    LOGIN_GAME_ACCOUNT_LOCKED = 0x1C,
    LOGIN_NO_BATTLENET_MANAGER = 0x1D,
    LOGIN_NO_BATTLENET_APPLICATION = 0x1E,
    LOGIN_MALFORMED_ACCOUNT_NAME = 0x1F,
    LOGIN_USE_GRUNT = 0x20,
    LOGIN_TOO_FAST = 0x21,
    LOGIN_CHARGEBACK = 0x22,
    LOGIN_IGR_WITHOUT_BNET = 0x23,
    LOGIN_UNLOCKABLE_LOCK = 0x24,
    LOGIN_CONVERSION_REQUIRED = 0x25,
    LOGIN_STATE_INITIALIZED = 0x26,
    LOGIN_STATE_CONNECTING = 0x27,
    LOGIN_STATE_HANDSHAKING = 0x28,
    LOGIN_STATE_AUTHENTICATING = 0x29,
    LOGIN_STATE_AUTHENTICATED = 0x2A,
    LOGIN_STATE_FAILED = 0x2B,
    LOGIN_STATE_DOWNLOADFILE = 0x2C,
    LOGIN_STATE_FIRST_SECURITY = 0x2D,
    LOGIN_STATE_PIN = 0x2E,
    LOGIN_STATE_PIN_WAIT = 0x2F,
    LOGIN_STATE_MATRIX = 0x30,
    LOGIN_STATE_MATRIX_WAIT = 0x31,
    LOGIN_STATE_TOKEN = 0x32,
    LOGIN_STATE_TOKEN_WAIT = 0x33,
    LOGIN_STATE_CHECKINGVERSIONS = 0x34,
    LOGIN_STATE_DISCONNECTED = 0x36,
    LOGIN_STATE_SURVEY = 0x37,
}

public enum CharLoginResult
{
    CHAR_LOGIN_IN_PROGRESS = 0x47,
    CHAR_LOGIN_SUCCESS = 0x48,
    CHAR_LOGIN_NO_WORLD = 0x49,
    CHAR_LOGIN_DUPLICATE_CHARACTER = 0x4A,
    CHAR_LOGIN_NO_INSTANCES = 0x4B,
    CHAR_LOGIN_FAILED = 0x4C,
    CHAR_LOGIN_DISABLED = 0x4D,
    CHAR_LOGIN_NO_CHARACTER = 0x4E,
    CHAR_LOGIN_LOCKED_FOR_TRANSFER = 0x4F,
    CHAR_LOGIN_LOCKED_BY_BILLING = 0x50,
}
