using System;
using System.IO;
using System.Linq;
using System.Text;
using LibGit2Sharp;

namespace GitExtractor
{
    class Program
    {
        static void Main(string[] args)
        {
            string branchName = "master";
            int commitCount = 0;

            using var git = new Repository(Repository.Discover(@"./"));
            if (git != null)
            {
                branchName = git.Head.FriendlyName;
                commitCount = git.Commits.Count();
            }

            StringBuilder sb = new();

            sb.AppendLine("// This file was automatically generated by the git extractor.");
            sb.AppendLine("// There is no need to modify this file.");
            sb.AppendLine();
            sb.AppendLine("#ifndef GIT_INFO_H");
            sb.AppendLine("#define GIT_INFO_H");
            sb.AppendLine();
            sb.AppendLine($"static const char* BRANCH_NAME = \"{branchName}\";");
            sb.AppendLine($"static int REVISION = {commitCount};");
            sb.AppendLine();
            sb.AppendLine("#endif");
            sb.AppendLine();

            File.WriteAllText("git_info.h", sb.ToString());
        }
    }
}